docs/contents/overview/01_architecture.rst

* Fixed invisible state diagram
* Corrected typos

Formatting issues, and diagram rendering corrected.

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/CounterMatcher.java
hermes-common/src/test/groovy/pl/allegro/tech/hermes/common/metric/counter/zookeeper/CounterMatcherTest.groovy
hermes-common/src/test/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporterTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/allegro/hermes/39)

10 add escapeHostname in CounterMatcher

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/ConsumerLatencyTimer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java

Alternative latency timer fix

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/SubscriptionEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/time/TimeFormatter.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/time/TimeFormatterTest.groovy
integration/src/integration/java/pl/allegro/tech/hermes/integration/KafkaRetransmissionServiceTest.java

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/allegro/hermes/66)

#44 retransmission accepts human readable date

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerHolder.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumersSupervisor.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/SubscriptionLocks.java

One more PR of the same changes but to rc this time.

Synchronized consumer supervisor

---

docs/contents/tech/01_deploy_frontend.rst
hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/HermesServer.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/SSLContextSupplier.java
integration/src/test/resources/config.properties

+ separate SSL switch from HTTP/2 
+ moved to faster (system dependent) SecureRandom implementation

#72 separate ssl/http2 switch, secure random fix

---

docker/build.sh
hermes-consumers/build.gradle
hermes-frontend/build.gradle
hermes-management/build.gradle

Conditionally applying gradle's "application" plugin, fixes #30

docker images build fix

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/MessageReader.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/PublishingServlet.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/callbacks/AsyncContextExecutionCallback.java

thread jump from kafka-network-thread to x-nio worker pool for listener execution

#128 thread jump from kafka-network-thread to x-nio worker pool

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageProducerFactory.java

Extended kafka producer config to give more flexibility with addressing issue with large requests

#128 extended kafka producer config

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/HermesMetrics.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Histograms.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/MessageReader.java

Added global histogram for message size.

135 added global histogram for message size

---

docs/contents/tech/02_deploy_consumers.rst
hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientFactory.java

143 made jetty request queues sizes equal to inflight size

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/SchemaEndpoint.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/CommonBinder.java
hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/schema/SchemaRepoClientFactory.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schemarepo/JerseySchemaRepoClient.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schemarepo/SchemaRepoClient.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schemarepo/SchemaRepoSchemaSourceProvider.java
hermes-common/src/test/java/pl/allegro/tech/hermes/domain/topic/schema/SchemaRepositoryTest.java
hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schemarepo/JerseySchemaRepoClientTest.java
hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schemarepo/SchemaRepoSchemaSourceProviderTest.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SchemaEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SchemaRepositoryConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SchemaRepositoryProperties.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/schema/SchemaSourceService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/schema/TopicFieldSchemaSourceRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/schema/schemarepo/SchemaRepoSchemaSourceRepository.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SchemaManagementTest.java
settings.gradle

Introduced external schema source implementation.
https://github.com/schema-repo/schema-repo

schema-repo external schema source implementation

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/HttpClientProperties.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/graphite/GraphiteClient.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/graphite/GraphiteConnectionException.java

Merges #178 to rc branch as well.

Move graphite timeout fix to rc

---

docker/docker-compose.yml
docker/latest/consumers/consumers.properties
docker/latest/frontend/frontend.properties
docker/latest/management/management.yaml
hermes-tracker-elasticsearch/build.gradle
hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/SchemaManager.java
hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepository.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/ElasticsearchResource.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/consumers/ConsumersElasticsearchLogRepositoryTest.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/frontend/FrontendElasticsearchLogRepositoryTest.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepositoryTest.java

chg string field types to not analyzed ("keyword type"), and booleanQuery to filterQuery(without scoring), for cleaner, smaller lucene index, and more efficient query.

Refactor elasticsearch mapping

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitter.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/kafka/broker/BrokerOffsetsRepository.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/KafkaBrokerOffsetsRepositoryTest.java

Fix for BrokerMessageCommiter -> now will invalidate broken channel on exception.

offset commiting to kafka fix

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/TopicProperties.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaBrokerTopicManagement.java

Setting unclean.leader.election.enable to false for newly created topics.

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SentMessageTrace.java
hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepository.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepositoryTest.java

Fixing order of discarded messages log, more restrictive tests.

Fix discarded messages log

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/MirroringSupervisorController.java

Added few logging messages which are essential to debug whether events are properly propagated in zk

204 adding more logging to debug mirroring alg

---

hermes-test-helper/build.gradle
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/retry/Retry.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/retry/RetryListener.java
hermes-tracker-elasticsearch/build.gradle
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/ElasticsearchResource.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/consumers/ConsumersElasticsearchLogRepositoryTest.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/frontend/FrontendElasticsearchLogRepositoryTest.java
hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepositoryTest.java
hermes-tracker-mongo/build.gradle
hermes-tracker/build.gradle
hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/consumers/AbstractLogRepositoryTest.java
hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/frontend/AbstractLogRepositoryTest.java
integration/build.gradle
integration/src/integration/java/pl/allegro/tech/hermes/integration/HermesClientPublishingTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/env/HermesIntegrationEnvironment.java

Introducing state-of-the-art retrying/stabilizing technology. False negatives are skipped and retried. Unstable tests can be found and reported in the next iteration if I figure out how to do it sensibly.

223 introduced RetryListener for more stable integration test suite

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaBrokerTopicManagement.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/BrokerOperations.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/IntegrationTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/env/ConsumersStarter.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/env/FrontendStarter.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/env/IntegrationTestKafkaNamesMapperFactory.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java
integration/src/integration/java/pl/allegro/tech/hermes/management/JsonToAvroKafkaNamesMappersConfiguration.java

I added integration test for check that after rollback topic still exists on broker.

281_add_int_test

---

.travis.yml

we will build only master, develop and pull requests

build only master & develop

---

circle.yml
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSenderTest.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/RemoteServiceEndpoint.java

let's try other CI, since Travis had a lot of problems with building Hermes lately (false positives) and is virtually undebuggable

configuring circle ci

---

hermes-console/static/js/console/Auth.js
vagrant_provisioning/install_console.sh

small fixes after running:
* overriding of JS variables
* fixed paths in Vagrant

hermes-console fixup

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/HermesPathParams.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/QueryEndpoint.java
hermes-common/src/main/java/pl/allegro/tech/hermes/domain/group/GroupRepository.java
hermes-common/src/main/java/pl/allegro/tech/hermes/domain/subscription/SubscriptionRepository.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperGroupRepository.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java
hermes-console/static/index.html
hermes-console/static/js/app.js
hermes-console/static/js/console/Search.js
hermes-console/static/partials/home.html
hermes-console/static/partials/search.html
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/GroupsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/QueryEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/group/GroupService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicContentTypeMigrationService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/query/matcher/LikeMatcher.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/query/matcher/MatcherFactories.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/query/parser/Operator.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/Hermes.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/HermesEndpoints.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java

- Query endpoint for all data
- New LIKE operator
- Closes #363

363 Search endpoint

---

docs/docs/user/subscribing.md
hermes-common/src/main/java/pl/allegro/tech/hermes/common/http/MessageMetadataHeaders.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/JsonMessageBatch.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatch.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/ConsumerRateLimiter.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/ApacheHttpClientMessageBatchSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/timeout/FutureAsyncTimeout.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSenderTest.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/test/MessageBuilder.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/RemoteServiceEndpoint.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchRetryPolicyTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java

also changed behavior of Retry-After not to slow down message sending when used

added Hermes-Retry-Count header in Consumers

---

hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html

386 console support for batch delivery

---

hermes-console/static/partials/modal/editSubscription.html

Batch properties are validated even when Serial delivery type is selected.

Subscription validation fix

---

Vagrantfile
vagrant_provisioning/conf/hermes-console-config.json
vagrant_provisioning/graphite.pp
vagrant_provisioning/init.sh
vagrant_provisioning/install_puppet_modules.sh
vagrant_provisioning/install_supervisord.sh

Added Graphite to Vagrant image

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/MonitoringDetails.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionHealth.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/SubscriptionEndpoint.java
hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/js/console/subscription/SubscriptionHealth.js
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/HealthConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/HealthProperties.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/SubscriptionHealthChecker.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/SubscriptionHealthContext.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/SubscriptionHealthContextCreator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/SubscriptionHealthProblemIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/SubscriptionMetrics.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/TopicMetrics.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/AbstractSubscriptionHealthProblemIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/LaggingIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/MalfunctioningIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/ReceivingMalformedMessagesIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/SlowIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/TimingOutIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/UnreachableIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/graphite/GraphiteClient.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionHealthCheckerTest.groovy
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/GraphiteEndpoint.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java

356: Hermes is subscription-monitoring friendly

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerFactory.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumersSupervisor.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerTest.java

move createMessageReceiver to SerialConsumer

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/preview/PreviewMessageLogReadRepository.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperPaths.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperPreviewMessageLogReadRepository.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/FrontendBinder.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/factories/PreviewMessageLogFactory.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/PublishingServlet.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/preview/PreviewMessageLog.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/preview/PreviewMessagePersister.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/preview/ZookeeperPreviewMessageLog.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/HermesServer.java
hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/publishing/message/preview/ZookeeperPreviewMessageLogTest.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/StorageConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java

Preview raw content from messages published on frontend in management. 
Endpoints:
/topics/{topicName}/preview -> return list of preview messages content as JSON
/topics/{topicName}/preview/{idx} -> return one preview message as octet-stream

195 preview

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentPathSerializer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkTracker.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkTrackerTest.java

Removing inactive subscription assignment entry from zk

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java

This is quickfix to survive until we're done with new consumer implementation.

467 quickfix for blocking consumers

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/JsonMessageBatch.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatch.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/FilteringMessageReceiver.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiver.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/ApacheHttpClientMessageBatchSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestFactory.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSender.java
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/batch/JsonMessageBatchTest.groovy
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverTest.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/test/MessageBuilder.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchDeliveryTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringJsonTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java

Subscription message-independent headers

---

.travis.yml
config/checkstyle/checkstyle.xml

Integration with https://sputnik.ci
@pbetkier - as we discussed, could you merge it and go through configuration in Sputnik.ci: https://github.com/TouK/sputnik-ci/wiki
With the latest version of Sputnik it's now possible to manually point to config files for checkstyle etc.

Sputnik.ci integration. 

---

docs/docs/user/publishing.md

Creating groups and topics was a bit outdated for a couple of months.

Update publishing docs: creating groups and topics

---

hermes-frontend/build.gradle

512 undertow updated to 1.3.23.Final

---

config/checkstyle/checkstyle.xml
hermes-api/src/main/java/pl/allegro/tech/hermes/api/EndpointAddressResolverMetadata.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
hermes-api/src/test/groovy/pl.allegro.tech.hermes.api/EndpointAddressResolverMetadataTest.groovy
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/MessageBatchSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/ProtocolMessageSenderProvider.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/ApacheHttpClientMessageBatchSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyHttpMessageSenderProvider.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/EndpointAddressResolver.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/InterpolatingEndpointAddressResolver.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/ResolvableEndpointAddress.java
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSenderTest.groovy
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSenderTest.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/InterpolatingEndpointAddressResolverTest.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/MultiUrlEndpointAddressResolver.java

Introducing EndpointAddressResolverMetadata. `Map` implementation.
resolves #514

Subscription EndpointAddressResolverMetadata

---

hermes-console/config.json.example
hermes-console/static/index.html
hermes-console/static/js/app.js
hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/js/directives/emptyToNull.js
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html

Adds additional fields to "Edit subscription" modal.

Subscription metadata in console

---

hermes-console/static/js/console/topic/TopicController.js

Subscription creation in console bugfix

---

docs/docs/configuration/console.md
docs/docs/user/subscribing.md
hermes-api/src/main/java/pl/allegro/tech/hermes/api/EndpointAddressResolverMetadata.java

...smuggling a warning suppression. :>

Filtering, metadata docs

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/EndpointAddress.java
hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java

fix BasicAuth credentials update

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatchReceiver.java

This is a bug with double wrapping of batched messages if they happen to end up in inflight queue.

fix batch messages double wrapping

---

build.gradle
hermes-api/src/main/java/pl/allegro/tech/hermes/api/BatchSubscriptionPolicy.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/EndpointAddress.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicName.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/kafka/KafkaTopic.java
hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/schema/CompiledSchema.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionOffsetChangeIndicator.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/HierarchicalCache.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/counter/DistributedEphemeralCounter.java
hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionOffsetChangeIndicatorTest.groovy
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/StorageConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/schema/ZookeeperSchemaSourceRepository.java

`guava.Objects` and `curator.EnsurePath` got deprecated

use Curator 2.11 and Guava 19.0

---

docs/docs/user/java-client.md
hermes-client/build.gradle
hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesClient.java
hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesClientBuilder.java
hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/HermesClientMetricsTest.groovy
hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/HermesClientTest.groovy

I used external library failsafe (https://github.com/jhalterman/failsafe)

(Resolving #481) adding exponential delay between retries

---

hermes-console/static/js/app.js
hermes-console/static/js/console/MetricStoreUrlResolver.js

Fixing lag metric path for groups/topics/subscriptions that contain `_` character in name.

Console lag metrics path fix

---

docs/docs/user/subscribing.md

We've been missing the OAuth2 support docs, so here they are. ;)

OAuth 2 support docs

---

config/pmd/pmd.xml
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/PublishingServlet.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/kafka/KafkaConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/retransmit/KafkaRetransmissionService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/retransmit/KafkaTimestampExtractor.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorTest.groovy
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CouldNotFetchSchemaVersionException.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CouldNotLoadSchemaException.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/DirectCompiledSchemaRepository.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaNotFoundException.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClient.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClient.java
hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/DirectCompiledSchemaRepositoryTest.groovy
integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java

Schema-related frontend responses fix

---

hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CachedSchemaVersionsRepository.java
hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/NoSchemaVersionsFound.java
hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/CachedSchemaVersionsRepositoryTest.groovy

fixed bug with clearing versions cache when hitting malfunctioning schema repo node

640 fixed bug with clearing versions cache

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/HermesMetrics.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Histograms.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/ConsumersRuntimeMonitor.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/BalancingJob.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/SelectiveWorkBalancer.java

introduces gauges in consumers-workload metrics

---

docs/docs/configuration/buffer-persistence.md
docs/docs/configuration/frontend-tuning.md
hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/hook/HooksHandler.java
hermes-frontend/build.gradle
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/HermesFrontend.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoader.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/cache/topic/NotificationBasedTopicsCache.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/cache/topic/TopicsCache.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/FrontendBinder.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/metric/CachedTopic.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/BrokerMessageProducer.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/CompletableFuturesHelper.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/MetadataLoadingResult.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/SchemaLoadingResult.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/TopicMetadataLoader.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/TopicMetadataLoadingStartupHook.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/TopicSchemaLoader.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/TopicSchemaLoadingStartupHook.java
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/server/CachedTopicsTestHelper.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/server/CompletableFuturesHelperTest.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/server/TopicMetadataLoadingStartupHookTest.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/server/TopicSchemaLoadingStartupHookTest.groovy
hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoaderTest.java
integration/src/test/resources/config.properties

Frontend hooks for topic metadata and schema load
fixes #591

Frontend graceful startup

---

build.gradle
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java

This PR causes topics to be validated before saving them to storage.
fixes #671

Validate topic before saving to storage

---

hermes-console/package.json
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java

Adds audit of subscription state changes

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java

fixes ugly bug with updating topic.maxMessageSize
#655

fixed topic equals #655

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionMetrics.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicMetrics.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Meters.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultErrorHandler.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultSuccessHandler.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/metric/CachedTopic.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridTopicMetricsRepository.java

Added throughput metrics for producer and consumer.
#681

681 added throughput metric

---

hermes-console/package.json
hermes-console/serve.js

Do not merge topic.contentType with default value #685

---

docs/docs/user/subscribing.md

Fix documentation - Retransmission takes is a PUT

---

docker/docker-compose.yml
docker/latest/consumers/Dockerfile
docker/latest/consumers/consumers.properties
docker/latest/consumers/logback.xml
docker/latest/frontend/Dockerfile
docker/latest/frontend/frontend.properties
docker/latest/frontend/logback.xml

@miguelpuyol i been trying to test your PR and found some more places to improve, not to mess up with your PR i decided to create my own that was based on your - i hope this is okay with you?
I also switched to official Confluent Kafka docker images. They are bit bigger than `wurstmeister` ones, but things seem to work stable on them.

Fix docker-compose and docker setup

---

build.gradle

Use Curator 2.11.1

---

.gitignore
scripts/README.md
scripts/migrate_consumers_0.10.5.py
scripts/requirements.txt

Adding admin scripts catalogue with first script for migrating consumers to 0.10.5

Admin scripts

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/blacklist/BlacklistZookeeperNotifyingCache.java

Fixing https://github.com/allegro/hermes/issues/717

Null check for cache event in BlacklistZookeeperNotifyingCache

---

CHANGELOG.md
docs/docs/configuration/security.md
docs/docs/user/permissions.md
hermes-console/package.json
mkdocs.yml

Changelog and docs updates for release 0.11.0.

Prepare for release 0.11.0

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporter.java
hermes-common/src/test/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporterTest.java
hermes-console/static/partials/modal/editGroup.html
integration/src/integration/java/pl/allegro/tech/hermes/integration/MetricsTest.java

Topics with underscore have invalid metrics paths in zookeeper

---

docs/docs/configuration/publishing-security.md
docs/docs/user/permissions.md
hermes-api/src/main/java/pl/allegro/tech/hermes/api/PublishingAuth.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/TopicHandler.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/TopicBuilder.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/TopicAuthorisationTest.java
mkdocs.yml

* added docs and changed
* topic.auth.unauthorisedAccessEnabled ->  topic.auth.unauthenticatedAccessEnabled

topic auth docs added

---

hermes-console/static/js/console/subscription/SubscriptionController.js

Resetting OAuth password in console fix

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/MessageFilterSpecification.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/HermesConsumersBuilder.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/header/HeaderPredicate.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/header/HeaderSubscriptionMessageFilterCompiler.java
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/filtering/HeaderMessageFilterSpec.groovy
integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringHeadersTest.java

This PR introduces a new type of message filter and registers it in `FilterChain`. 
closes #753

Add filtering by headers #753

---

hermes-console/config.json.example
hermes-console/static/index.html
hermes-console/static/js/console/topic/TopicRepository.js
hermes-console/static/js/directives/bindHtml.js
hermes-console/static/partials/topic.html
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/schema/validator/SchemaValidatorProvider.java
integration/build.gradle
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SchemaManagementTest.java

Configuring custom view near topic buttons area on UI.
I will use this space to add migration button for JSON topics. The button will forward a user to an external migration tool.
This PR fixes also NPE threw by schema save endpoint on JSON topic.

Custom button on ui

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/ssl/JvmKeystoreSslContextFactory.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/ssl/KeystoreProperties.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/ssl/SslContextFactory.java
hermes-console/package.json
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html
hermes-consumers/build.gradle
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/HermesConsumers.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/oauth/client/OAuthClient.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/oauth/client/OAuthHttpClient.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientFactory.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestFactory.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyHttpMessageSenderProvider.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/SslContextFactoryProvider.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/di/ConsumersBinder.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/HermesFrontend.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/ConsumingHttp2Test.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/CustomSslContextFactoryTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/HermesClientPublishingTest.java
mkdocs.yml

Added basic support for http2 delivery to hermes-consumer.

added http2 client to consumers

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/NonblockingConsumersSupervisor.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/Signal.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilter.java
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessTest.groovy
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerStub.groovy
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilterTest.groovy

Generating unique ids for init signals in hermes-consumers and propagating them to children signals. Solves #772

Creating consumer signals chains

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/CommonBinder.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/DeserializationMetrics.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/MessageContentWrapper.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/SchemaAwareSerDe.java
hermes-common/src/test/java/pl/allegro/tech/hermes/common/message/wrapper/MessageContentWrapperTest.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/MessageConfiguration.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/avro/AvroUser.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/MessageBufferLoadingTest.java

Adding fallback from schema version aware deserialization to any schema deserialization. Solves #779

Schema version aware deserialization is backward compatible

---

.travis.yml
hermes-benchmark/README.md
hermes-benchmark/build.gradle
hermes-benchmark/src/jmh/resources/config.properties
hermes-consumers/build.gradle
integration/build.gradle

Fixing benchmarks as they stopped running while ago due to code changes. I also decided to add them (with short duration of execution) to travis-ci only to verify whether they are working. Thanks this developers who break benchmarks will get info about it and will be able to fix this issue.

Benchmarks fix

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/CommonBinder.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/MessageContentWrapper.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/SchemaOnlineChecksRateLimiter.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/SchemaOnlineChecksWaitingRateLimiter.java
hermes-common/src/test/java/pl/allegro/tech/hermes/common/message/wrapper/MessageContentWrapperTest.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/MessageConfiguration.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/MessageBufferLoadingTest.java

Message wrapper schema online checks rate limiting

---

docs/docs/configuration/secure-transport.md

* Update Consumer SSL config changes to match the 0.12.0

 Consumer SSL config changes to match the 0.12.0

---

docs/docs/user/subscribing.md

* Add required fields in the create subscription call 
* Correct the Json Payload in Subscription docs

Minor documentation fix

---

hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/LogSchemaAware.java
hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/consumers/ConsumersElasticsearchLogRepository.java
hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/frontend/FrontendElasticsearchLogRepository.java
hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepository.java

Adds additional timestamp_seconds field for sorting in Elastic Search tracker

---

build.gradle
hermes-common/build.gradle
hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperGroupRepositoryTest.groovy
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilter.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/mirror/MirroringSupervisorController.java
integration/build.gradle
integration/src/integration/java/pl/allegro/tech/hermes/integration/ConsumingHttp2Test.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/GroupManagementTest.java

Update kafka libs

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionNameWithMetrics.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/QueryEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/QueryEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java

Added endpoint for querying subscriptions metrics.

Query subscriptions metrics

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Group.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicName.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/constraints/Names.java
hermes-console/static/partials/modal/editGroup.html
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/modal/editTopic.html
integration/src/integration/java/pl/allegro/tech/hermes/integration/MetricsTest.java

Special chars restriction in group, topic and subscription name

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/AvroEncodedJsonAvroConverter.java
hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageContentTypeEnforcerTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java

Log detailed info

---

docs/docs/user/topic-preview.md
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PreviewHandler.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageToJsonConverter.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewFactory.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewLog.java
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/message/MessageToJsonConverterTest.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewFactoryTest.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewLogTest.groovy

Decodes avro message for preview (writes to zookeeper decoded value). If it fails, raw message is previewed. For json, behaviour is not changed.

resolve #821 | decoding avro message to json for preview

---

hermes-console/static/css/main.css
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/modal/editTopic.html

Tooltips with help messages are now visible in add/edit for topic and subscription.

Adds tooltips when adding or editing topic/subscription

---

integration/build.gradle

New version of alpn for new version of jdk8

new release ALPN for jdk8

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
hermes-common/build.gradle
hermes-consumers/build.gradle
hermes-mock/build.gradle
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMock.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockDefine.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockException.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockExpect.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockHelper.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockQuery.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockRule.java
hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/Request.java
hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockAvroTest.groovy
hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockTest.groovy
hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/TestMessage.groovy
hermes-mock/src/test/resources/msg.avsc
hermes-schema/build.gradle
integration/build.gradle
settings.gradle

Feature #858 Hermes mock

---

docs/docs/configuration/rate-limiting.md
docs/docs/user/subscribing.md
hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperPaths.java
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/HermesConsumers.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateCalculator.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateCalculatorJob.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateRegistry.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateSupervisor.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/StrictMaxRateProvider.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/SubscriptionConsumersCache.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/di/ConsumersBinder.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentCache.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentCaches.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentRegistryFactory.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateRegistryTest.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkTrackerTest.java

Revert "Rate limit negotiation applied to local Data Center only"

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/SubscriptionOwnershipEndpoint.java
hermes-common/src/main/java/pl/allegro/tech/hermes/domain/subscription/SubscriptionRepository.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java
hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepositoryTest.groovy
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsOwnershipEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionOwnerCache.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicOwnerCache.java
hermes-management/src/main/resources/application.yaml
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/Hermes.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/HermesEndpoints.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ListSubscriptionForOwnerTest.java
integration/src/test/resources/application-integration.yaml

This PR is analogical to https://github.com/allegro/hermes/pull/886 but except caching OwnerId to TopicName it caches OwnerId to SubscriptionName

Listing subscriptions by their owner

---

docs/docs/user/subscribing.md
hermes-console/static/partials/modal/editSubscription.html

Fixes: https://github.com/allegro/hermes/pull/894/files#r209167187

fix label: seconds -> milliseconds

---

hermes-console/static/css/main.css
hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/js/console/subscription/SubscriptionFactory.js
hermes-console/static/js/console/subscription/SubscriptionRepository.js
hermes-console/static/js/console/topic/TopicController.js
hermes-console/static/partials/modal/editSubscription.html

Subscription filter on UI

---

hermes-console/static/partials/subscription.html

Show filters on subscription page

---

hermes-management/build.gradle

Adding health status endpoint to hermes-management

---

hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/js/console/topic/TopicController.js
hermes-console/static/partials/modal/editTopic.html
hermes-console/static/partials/subscription.html
hermes-console/static/partials/topic.html

Resolves #846:
- Added **clone** action for topics:
- Added **clone** action for subscriptions:

Added clone action for topics and subscriptions

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentRegistry.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/BalancingJob.java

In order to catch any exceptions that may occur during writing to assignment registry.

More logging on writing to consumer assignment registry

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/query/MatcherQuery.java

The author of the original changes is @iwko

Additional logging for MatcherQuery

---

hermes-console/static/js/console/subscription/SubscriptionController.js

Due to lack of last commit in PR https://github.com/allegro/hermes/pull/995 I'm adding it here.

Fix consumer groups url in console

---

CHANGELOG.md

Changelog for 0.16.0 version

---

docs/docs/quickstart.md
vagrant_provisioning/install_kafka.sh

Updated Kafka version in Vagrant as previous version stopped being available in mirror server.

Updates Kafka version in Vagrant as previous one stopped being available

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/timeout/FutureAsyncTimeout.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/queue/MonitoredMpscQueue.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java

More logging in order to fix offset committing issues.

Offsets committer log

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionNameWithMetrics.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicNameWithMetrics.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java

Exposing volume metric in metrics query endpoint

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/storage/StorageConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridTopicMetricsRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/SummedDistributedEphemeralCounter.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/SummedSharedCounter.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/health/HealthCheckTaskTest.groovy
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepositoryTest.groovy
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridTopicMetricsRepositoryTest.groovy
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/SummedDistributedEphemeralCounterTest.groovy
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/SummedSharedCounterTest.groovy
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/zookeeper/ZookeeperClientManagerTest.groovy
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/utils/MultiZookeeperIntegrationTest.groovy

1065 summed counter values

---

hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesClient.java
hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesMessage.java
hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesResponse.java
hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesResponseBuilder.java
hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/HermesClientTest.groovy

Original message available on HermesResponse when it wasn't published.

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/schema/validator/InvalidSchemaException.java

Including schema validation error details in management responses

---

docs/docs/quickstart.md

Resolves #1121 | Changed url of service mock in QuickStart guide

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java

fixes #1070 
I was trying to write a test for this, but it's too hard because of the way consumer message sender is implemented.

Inflight messages counter decrement after sender shutdown

---

hermes-client/src/main/java/pl/allegro/tech/hermes/client/metrics/MetricsMessageDeliveryListener.java

Remove jersey repackaged immutable map reference

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientFactory.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSenderTest.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/RemoteServiceEndpoint.java

Added global flag for enabling redirects. By default they are disabled. Solves #1126

Resolves #1126 | Redirects are disabled by default

---

hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html

This is how it looks on Subscription page:
This is how it look in edit modal:

resolve #1043 |  Enables Http header filtering

---

hermes-console/static/partials/group.html
hermes-console/static/partials/groups.html
hermes-console/static/partials/subscription.html
hermes-console/static/partials/topic.html
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/EndpointConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/JerseyProperties.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/JerseyResourceConfig.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/ConsumerGroupManager.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/MultiDCAwareService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/BrokersClusterService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaConsumerGroupManager.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/NoOpConsumerGroupManager.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaConsumerGroupManagerSpec.groovy
integration/build.gradle

This PR introduces changes to few different functionalities on a branch develop. Therefore I suggest to review it by commits. 
Improvements:
* used Kafka topic name mapper in KafkaConsumerGroupManager. Also changed place where this manager is called. Now it is called before subscription creation. Thanks to this hermes-consumer creates subscription after kafka consumer group is created in hermes-management.
* Extended Jersey configuration in hermes-management. We need this change to expose spring boot actuator endpoints.
* added popovers displayed near disabled buttons when user isn’t signed in
* hermes-console footer can be configured via hermes-management config

Develop branch improvements

---

hermes-console/package.sh

restoring node command in th path

---

docs/docs/user/subscribing.md
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/MessageSendingResult.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/SingleMessageSendingResult.java
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/MultiMessageSendingResultTest.groovy
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java

Retry on 429

---

hermes-api/build.gradle

java11 fix: jaxb deps upgrade

---

docs/docs/configuration/console.md
docs/docs/configuration/message-tracking.md
docs/docs/configuration/schema-repository.md
docs/docs/deployment/deployment.md

Recently we got some questions about the schema repository so I decided to update the documentation. Additionally I fixed few typos.

Schema repository docs improvement

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/UnhealthyEndpoint.java

Instead of 200 with `[]` it returns 404 `{"message":"Owner of id 'yyyy' not found in source xxx","code":"OWNER_NOT_FOUND"}` when owner not found.

Resolve #1172 | Return error response when owner not found

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java
hermes-api/src/test/java/pl/allegro/tech/hermes/api/SubscriptionTest.java
hermes-console/static/js/console/subscription/SubscriptionFactory.js
hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java
hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringJsonTest.java

Exponential retry policy for failed requests in serial subscription.

SKYEDEN-981 | Exponential retry policy

---

build.gradle
hermes-management/build.gradle

kafka libraries upgraded to version 2.2.2

---

hermes-console/static/partials/modal/editSubscription.html
hermes-console/static/partials/subscription.html

Fixed hermes console for batch subscription.

FIX | Exponential retry policy

---

docker/docker-compose.yml
docker/latest/consumers/Dockerfile
docker/latest/frontend/Dockerfile
docker/latest/management/Dockerfile
docker/latest/management/management.yaml

Dockerfiles have been updated. The project is now automatically built by dockerhub.

Docker update

---

docs/docs/quickstart.md
docs/docs/user/subscribing.md

- exponential retry policy added to subscription section
- docker guide added to quickstart section

Hermes docs update

---

docker/docker-compose.yml
docker/latest/consumers/consumers.properties
docker/latest/frontend/frontend.properties

- schema registry image added to docker-compose
- schema registry properties added to frontend and consumer configs

Schema registry added to docker

---

CHANGELOG.md

Changelog update up to release 1.4.14. Fixed faulty formatting.

Changelog update and fix

---

hermes-console/static/js/console/Groups.js
hermes-console/static/partials/groups.html

[console] Preserving filter value in groups list

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/AvroCompiledSchemaRepositoryFactory.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/SchemaCacheRefresherCallback.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/SchemaVersionsRepositoryFactory.java

Resolves #1257 | A topic change updates its all cached schemas

---

docs/docs/quickstart.md

- a new section in quickguide regarding docker image building
- fix in quickguide

Adding new section "Building your own docker image" to docs

---

docs/docs/configuration/internal-format.md

resolve #1154 | fixed internal format docs

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java

Manager now creates topic in Kafka before attempting to save it in ZK

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/MessageReadHandler.java
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/handlers/DefaultResponseSimulatorTest.groovy

Resolves [#1294](https://github.com/allegro/hermes/issues/1294)
Change default undertow response status

Change default undertow http status code

---

hermes-console/static/js/console/Groups.js
hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/js/console/topic/TopicController.js
hermes-console/static/partials/subscription.html

Avoid clearing unsaved add/edit topic/subscription forms when closing modal.

resolve #954 | Avoid clearing unsaved forms

---

hermes-console/Gruntfile.js
hermes-console/package.json
hermes-console/serve.js
hermes-console/static/js/bootstrap.js
hermes-console/static/js/console/Discovery.js
hermes-console/static/js/console/Groups.js
hermes-console/static/js/console/Mode.js
hermes-console/static/js/console/Search.js
hermes-console/static/js/console/constraints/ConstraintsController.js
hermes-console/static/js/console/constraints/ConstraintsRepository.js
hermes-console/static/js/console/filters/FiltersDebugger.js
hermes-console/static/js/console/owner/OwnerSelector.js
hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/js/console/subscription/SubscriptionHealth.js
hermes-console/static/js/console/topic/TopicController.js
hermes-console/static/js/console/topic/TopicRepository.js
hermes-console/static/js/filters/readableSize.js

* Bump jshint from 0.11.0 to 0.11.3
* Replace invalid path`/js` with `/static/js`
* Fix previously undetected errors

resolve #1284 | Fix jshint config and previously not detected errors

---

build.gradle
hermes-client/build.gradle
hermes-common/build.gradle
hermes-management/build.gradle
hermes-test-helper/build.gradle

These changes should fix the following vulnerabilities:
https://github.com/advisories/GHSA-4w82-r329-3q67
https://github.com/advisories/GHSA-5949-rw7g-wx7w
https://github.com/advisories/GHSA-6hgm-866r-3cjv
https://github.com/advisories/GHSA-c265-37vj-cwcc
https://github.com/advisories/GHSA-c2q3-4qrh-fm48
https://github.com/advisories/GHSA-gjmw-vf9h-g25v
https://github.com/advisories/GHSA-gww7-p5w4-wrfv
https://github.com/advisories/GHSA-j823-4qch-3rgm
https://nvd.nist.gov/vuln/detail/CVE-2017-18640
https://nvd.nist.gov/vuln/detail/CVE-2017-5929
https://nvd.nist.gov/vuln/detail/CVE-2019-0232
https://nvd.nist.gov/vuln/detail/CVE-2019-10072
https://nvd.nist.gov/vuln/detail/CVE-2019-12418
https://nvd.nist.gov/vuln/detail/CVE-2019-17563
https://nvd.nist.gov/vuln/detail/CVE-2020-10663 …

Bump tools versions to fix vulnerabilities

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/FilteredMessageHandler.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java

Add configurable filtering ratelimiter

Add configurable filtering ratelimiter

---

hermes-frontend/build.gradle
hermes-management/build.gradle

so the docker image would be downloaded correctly.

Updated dependencies version for testcontainers

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/PersistentSubscriptionMetrics.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionMetricsRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepository.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepositoryTest.groovy

Endpoint serving zookeeper metrics for subscription.

Subscription zookeeper metrics endpoint

---

README.md
hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionHealthProblem.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/SubscriptionHealthContext.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/LaggingIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/MalfunctioningIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/ReceivingMalformedMessagesIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/TimingOutIndicator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/health/problem/UnreachableIndicator.java
hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionHealthCheckerTest.groovy
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ListUnhealthySubscriptionsForOwnerTest.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java

Subscription name in description for subscription health problems.

Improved subscription logging

---

build.gradle

Thanks to this change publishing to local maven repository (`./gradlew publishToMavenLocal`) works as expected.

Packages signing enabled only when env var GPG_KEY_ID is set

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaBrokerTopicManagement.java

Previously, `KafkaBrokerTopicManagement` was not waiting for topic created confirmation from Kafka. Now we can handle topic creation failures, and return correct error to end user.

Waiting for KafkaFeature during topic creation

---

hermes-api/src/main/java/pl/allegro/tech/hermes/api/MessageTextPreview.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/TopicEndpoint.java
hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/converter/AvroRecordToBytesConverter.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PreviewHandler.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageToJsonConverter.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewFactory.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewLog.java
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/message/MessageToJsonConverterTest.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewFactoryTest.groovy
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewLogTest.groovy
integration/src/integration/java/pl/allegro/tech/hermes/integration/env/FrontendStarter.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/MessagePreviewIntegrationTest.java

I've tried to write some integration test in ZookeeperMessagePreviewRepositoryTest but failed on missing dependencies to MessagePreviewLog which is inside hermes-frontend, do you see how to test it as a whole?

Fix preview for avro topic with schemaId aware serialization

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/owner/validator/EndpointOwnershipValidator.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/validator/SubscriptionValidator.java

Added EndpointOwnershipValidator interface with empty implementation. Thanks to this we can create complex bean to create logic validating if provided endpoint and provided subscription owner match.

Added EndpointOwnershipValidator

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/FrontendBinder.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducer.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducerFactory.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/MessageToKafkaProducerRecordConverter.java
hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducerIntegrationTest.groovy
hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducerTest.java

This PR is similar to #1479 but for frontend part. Motivation is also the same: to be able to test some corner cases without usage of integration test

Refactor: Message to kafka ProducerRecord conversion logic extracted from KafkaBrokerMessageProducer

---

hermes-console/static/css/main.css
hermes-console/static/partials/search.html

Increased the width of the search bar for issue #1488

---

CHANGELOG.md
hermes-console/config.json.example
hermes-console/config_default.json
hermes-console/static/index.html
hermes-console/static/js/app.js
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java

Added environment label in hermes-console and updated CHANGELOG

---

hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/CuratorClientFactory.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/zookeeper/ZookeeperClientManager.java

According to [this issue](https://github.com/allegro/hermes/issues/702)
Currently Hermes does not protect the data kept in Zookeeper. It is possible to set username/passwd in Curator, but it is only used to read data. All new nodes are by default visible to everyone.
This PR fix this issue, according to https://stackoverflow.com/questions/40427700/using-acl-with-curator :
> ACL in Apache Curator are for access control. That is, if you set ACLProvider as follows,
> 
```
new ACLProvider() {
@Override
public List<ACL> getDefaultAcl () {
return ZooDefs.Ids.CREATOR_ALL_ACL;
}
@Override
public List<ACL> getAclForPath (String path){
return ZooDefs.Ids.CREATOR_ALL_ACL;
}
}
```
> only the client with the credentials identical to the creator will be given access to the corresponding ZNode later on. …

Introduce ZK secure mode: Set Zookeeper ACLs on all created nodes

---

.github/workflows/release.yml

Fixed issues with:
- Authentication using GITHUB_TOKEN (`token` instead of `Bearer`),
- Building JSON body containing environment variables,
- Incorrect previous version detection

Fix automatic generation of release notes

---

build.gradle
hermes-console/package.json

Remove release hooks and version from console package.json

---

integration/src/integration/java/pl/allegro/tech/hermes/integration/setup/HermesManagementInstance.java

After this change the Hermes Management instance will wait for the structure creation on all Zookeeper clusters during the starting operation.

#1433 Wait for readiness of all Zookeeper clusters

---

build.gradle

This PR resolves: https://github.com/allegro/hermes/issues/1616

bump kafka-clients to 2.8.2

---

.github/workflows/gradle-wrapper-validation.yml

This resolves: https://github.com/allegro/hermes/issues/1627

add gradle wrapper validation

---

hermes-console/static/js/console/subscription/SubscriptionController.js
hermes-console/static/partials/subscription.html
hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java

Undelivered messages should only be visible to users with appropriate permissions (admin, theme owner, subscription owner)

Undelivered messages are invisible to unauthorized users

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubClient.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubClientsPool.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMessageSender.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMessageSenderProvider.java
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubClientsPoolTest.groovy
hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/googlepubsub/GooglePubSubMessageSenderTest.groovy

This PR fixes message compression in Pubsub subscription

Pubsub subscription compression fix

---

build.gradle
hermes-client/build.gradle
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperGroupRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/storage/StorageConfiguration.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/zookeeper/ZookeeperClient.java

Bump spring boot to 2.7.7.
Additionally, move checking whether `groups` path is created out of `StorageConfiguration` - there was circular dependency error after upgrade. See: https://github.com/spring-projects/spring-framework/issues/27876 for details.

bump spring boot to 2.7.7

---

build.gradle
hermes-client/build.gradle
hermes-mock/build.gradle
hermes-test-helper/build.gradle

Bump Wiremock to 3.0.1

---

.github/workflows/ci.yml

Parse test results and put summary + table with failed and skipped tests into GitHub job summary

Generate test summary in CI workflow

---

hermes-console-vue/package.json
hermes-console-vue/src/config/ace-config.ts
hermes-console-vue/src/i18n/en-US/index.ts
hermes-console-vue/src/i18n/en-US/topic-form.ts
hermes-console-vue/src/views/topic/topic-form/TopicForm.vue
hermes-console-vue/yarn.lock

ACE component for AVRO schema.
Features:
- code coloring with json support
- errors detection for json
- auto formatting - beautify button
Dark mode support:

Hermes console 2 | JSON auto formatting with code highlighting for AVRO schema.

---

hermes-console-vue/src/i18n/en-US/index.ts
hermes-console-vue/src/views/topic/subscriptions-list/SubscriptionsList.vue

filtering subscription list in topic view

---

hermes-console-vue/src/components/key-value-card/key-value-card-item/KeyValueCardItem.vue

This change is to allow copying property names to the clipboard
Issue https://github.com/allegro/hermes/issues/1751

Hermes console vue issue1751

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java

Anonymize password in subscription query

---

hermes-console-vue/src/i18n/en-US/index.ts
hermes-console-vue/src/views/topic/schema-panel/AvroTypes.ts
hermes-console-vue/src/views/topic/schema-panel/SchemaPanel.spec.ts
hermes-console-vue/src/views/topic/schema-panel/SchemaPanel.vue
hermes-console-vue/src/views/topic/schema-panel/avro-viewer/AvroNode.vue
hermes-console-vue/src/views/topic/schema-panel/avro-viewer/AvroViewer.vue

Vue component for Avro schema pretty formatting with light/dark theme support.

Avro pretty format view component.

---

.github/workflows/checkstyle.yml
hermes-api/src/main/java/pl/allegro/tech/hermes/api/Stats.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionStats.java
hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicStats.java
hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/MetricsDashboardUrl.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/consistency/DcConsistencyService.java
hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/console/FrontendRoutesFilter.java
integration/src/integration/java/pl/allegro/tech/hermes/integration/management/StatsTest.java

Non-existent topic would cause consistency check to fail

check topic existence before listings its subscriptions

---

.github/workflows/checkstyle.yml
.github/workflows/ci-console.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/markdown-links-check.yml
.github/workflows/release.yml
.github/workflows/test_report.yml

In this PR I've bumped GH Action versions and adjusted Gradle cache (by adding `gradle/gradle-build-action`).
To improve CI process

Update GH Actions, adjust Gradle cache

---

integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/QueryEndpointTest.java

Fix: Use random group name in the parameterized test and use `publishUntil()`.

Fixed shouldQueryTopicsMetrics test

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/BrokerLatencyReporter.java

Allow broker reporter tasks to be dropped without propagating exception

allow tasks to be rejected

---

docs/docs/configuration/buffer-persistence.md
docs/docs/user/publishing.md
hermes-console/src/components/console-alert/ConsoleAlert.vue
hermes-console/src/composables/topic/use-create-topic/useCreateTopic.ts
hermes-console/src/composables/topic/use-form-topic/types.ts
hermes-console/src/composables/topic/use-form-topic/useFormTopic.ts
hermes-console/src/dummy/topic-form.ts
hermes-console/src/i18n/en-US/index.ts
hermes-console/src/i18n/en-US/topic-form.ts
hermes-console/src/views/topic/topic-form/TopicForm.vue

- add buffers deprecation notice
- add info about remote datacenter fallback

Improve ACK docs

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java

This is an attempt to resolve a problem with undeliverable Broadcast Messages. In the heap dump of Hermes consumer I have found a instance of a undeliverable `pl.allegro.tech.hermes.consumers.consumer.Message` with strange internal state:
`succeededUris` HashMap contained 3 nodes and was of size 4 which could suggest a [concurrent access](https://stackoverflow.com/questions/5283294/can-a-java-hashmaps-size-be-out-of-sync-with-its-actual-entries-size). And indeed it turns out that the `Message` can be modified from different threads from `deliveryReportingExecutor` and is being read from other threads e.g. `retrySingleThreadExecutor`. 
Since `Message` is accessed and modified from different threads I've decided to make it immutable where possible and synchronized access to mutable state

make message thread safe

---

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java
integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java

This reverts accidental commit 5cc4fe18ba83c1a94abeef65fa237d3e23847b05.

Revert accidental "improve fallback to remote dc validation"

---

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSender.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/readiness/AdminReadinessService.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/readiness/DefaultReadinessChecker.java

- add more visibility into readiness checks
- fix metadata NPE for unknown leader

Metadata loading improvements

---

hermes-console/src/utils/json-avro/avroTypes.ts
hermes-console/src/utils/json-avro/jsonAvroUtils.spec.ts
hermes-console/src/utils/json-avro/jsonAvroUtils.ts
hermes-console/src/utils/json-avro/jsonUtils.spec.ts
hermes-console/src/utils/json-avro/jsonUtils.ts
hermes-console/src/views/subscription/SubscriptionView.vue
hermes-console/src/views/subscription/filters-card/FiltersCard.vue
hermes-console/src/views/subscription/subscription-form/SubscriptionForm.vue
hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/SubscriptionPathFilters.vue
hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/SubscriptionPathFiltersDebug.vue
hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/path-filter-row/PathFilterRow.vue
hermes-console/src/views/subscription/subscription-metadata/SubscriptionMetadata.vue

Fixes: https://github.com/allegro/hermes/issues/1749 
Add autocomplete functionality to "Message content filters" on subscription form

Avro path schema autocomplete input.

---

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/BasicMessageContentReader.java
hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java

Add subscription / topic details to exceptions and logs related to message reading

add details to message reading logs

---

hermes-console/src/views/subscription/subscription-form/subscription-basic-filters/path-filter-row/PathFilterRow.vue
hermes-console/src/views/subscription/subscription-form/subscription-header-filters/SubscriptionHeaderFilters.vue
hermes-console/src/views/subscription/subscription-form/subscription-header-filters/header-filter-row/HeaderFilterRow.vue

This reverts commit 93f949d2f450772ed9ac20000d6261d14d3c8231.
Adding subscription header filters does not works after the change.

Revert "Debug subscription filters fix (#1967)"

---

build.gradle
hermes-client/build.gradle
hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesClient.java
hermes-frontend/build.gradle
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/TopicMetadataLoadingExecutor.java
hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/TopicSchemaLoader.java

Update failsafe as its current version causes problems when timeouts occur: https://github.com/failsafe-lib/failsafe/issues/348

Update failsafe library
