hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/MetricsTest.java
This is bugfix for issue with accidental zk node creation when asked for metrics of non-existing subscription.
=> #25 added check if subscription exists when asked for metrics

hermes-client/src/main/java/pl/allegro/tech/hermes/client/jersey/JerseyHermesResponse.java
This change fixes #40 where connections are not being closed if readEntity is not called on the response object.
=> fixing #40 jersey client connection closing

hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/SubscriptionEndpoint.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/TopicEndpoint.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/subscription/SubscriptionRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/HermesAPIOperations.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/MetricsTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java
Added listing of tracked topics and subscriptions. First iteration is without using any local caching. For performance reasons users can narrow scope via groupName query parameter.
=> 43 listing tracked topics and subscriptions

docker/Dockerfile-consumers, docker/Dockerfile-frontend, docker/Dockerfile-management, docker/latest/consumers/Dockerfile, docker/latest/frontend/Dockerfile, docker/latest/management/Dockerfile
Moving with docker images to `alpine-linux` (minimal linux distribution), same functionality, much smaller image size when compared to previous `java:8` base image:
```
REPOSITORY                        TAG     VIRTUAL SIZE
allegro/hermes-management         alpine  246 MB
allegro/hermes-consumers          alpine  213.7 MB
allegro/hermes-frontend           alpine  213.8 MB
allegro/hermes-frontend           latest  852.2 MB
allegro/hermes-management         latest  884.5 MB
allegro/hermes-consumers          latest  852.1 MB
```
=> docker images on alpine-linux

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
Fix for: consumers should treat 4xx response from "subscriptions without 4xx retry" as success
=> consumer 4xx output rate fix

hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/Waiter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/Waiter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java
Fixes such assertions:
```java
(…).until(() -> {
x.equals(y);
});
```
Such lambdas were treated as a `Runnable`, so since no exception was thrown the assertions did always pass. I replaced such lambdas with `() -> x.equals(y)`. Also simplified lambdas of this sort: `() -> { return x.equals(y); }` for brevity.
Also, did some minor refactorings for code reuse and removed `@Unreliable` annotations, since the tests do pass on Travis right now and assertions are now reliable :)
=> Fix for always-passing awaitility assertions in Waiter

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionMetrics.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionLagSource.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepository.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/metrics/NoOpSubscriptionLagSource.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/metrics/HybridSubscriptionMetricsRepositoryTest.groovy
adds subscription lag property to object returned by management's `topics/{topicName}/subscriptions/{subscriptionName}/metrics` endpoint. with no custom implementation of the lag provider `-1` is returned.
=> subscription lag source

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionName.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/subscription/SubscriptionRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperPaths.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/HermesConsumers.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/di/ConsumersBinder.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumersSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/LegacyMirroringSupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/MirroringSupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/SubscriptionAssignment.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/SubscriptionAssignmentAware.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/SubscriptionAssignmentPathSerializer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/SubscriptionAssignmentRegistry.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/SupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/SupervisorControllerFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/WorkTracker.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workTracking/WorkTrackerFactory.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumersSupervisorTest.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/Waiter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/Waiter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/GroupManagementTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java
Initial version of new consumer runtime model. Designed to be extended by introducing more advanced workload spread algorithms.
Two basic implementations are provided:
- **legacy.mirror** - consumers are mirroring each other without using new runtime model (legacy behaviour)
- **mirror** - consumers are mirroring each other using new runtime model, the difference between *legacy.mirror* is another level of indirection between change in *SubscriptionCache* and spawning new consumers
New runtime model is based on a structure in zk reflecting which consumer supervisor is assigned to which subscription. Structure looks as follows:
/hermes/consumers/**runtime**/*qualified_topic_name$subscription_name*/*(supervisor_id)+*
=> 204 initial version of new consumer runtime model

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Counters.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Gauges.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/HermesMetrics.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Histograms.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Meters.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Timers.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/CounterMatcher.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporter.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/BrokerAckAllLatencyTimer.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/BrokerAckLeaderLatencyTimer.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/ConsumerLatencyTimer.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/ProducerAckAllLatencyTimer.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/ProducerAckLeaderLatencyTimer.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/common/metric/counter/zookeeper/CounterMatcherTest.groovy, hermes-common/src/test/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporterTest.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultErrorHandler.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultSuccessHandler.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/di/ConsumersBinder.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/result/DefaultErrorHandlerTest.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/FrontendBinder.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/Producers.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/MessageReader.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/MetricsAsyncListener.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/callbacks/MetricsPublishingCallback.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/validator/MessageValidators.java
I refactored hermes metrics slightly and moved hostname to reporter prefix. This allows metric names to be free from host specific information and be queried from tag based metric repositories (like kairosDB).
=> 276 moved hostname to reporter prefix

hermes-common/src/main/java/pl/allegro/tech/hermes/common/hook/HooksHandler.java
Added closing LoggerContext on shutdown to support proper flush of AsyncAppender (http://logback.qos.ch/manual/appenders.html#AsyncAppender). It doesn't hurt other appenders.
=> 299 closing LoggerContext on shutdown for async appenders

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/CounterMatcher.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporter.java
both 'publish' and 'unpublish' counters have the same prefix,
since hosntame was removed, sometimes (data race) unpublished
was reported as published, which casuses us to lose topic
published messages metrics (they are no longer monotonic)
=> fixing bug in frotnend counter reporting

docs/docs/configuration/secure-transport.md, hermes-api/src/main/java/pl/allegro/tech/hermes/api/constraints/EndpointAddressValidator.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/MessageSenderFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientFactory.java, mkdocs.yml
Tested on MacOS X and Ubuntu 15 VM with [Mockbin](https://mockbin.org) used as a valid HTTPS subscriber endpoint.
=> HTTPS support in message senders

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SupervisorControllerFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/SelectiveSupervisorController.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java
This PR addresses the issue #320 by separating handling zk events from actual assignment processing. For instance handling onAssignmentRemoved will no longer block until actual consumer is killed.
=> 320 nonblocking subscription assignment processing for selective consumer workload

hermes-common/src/main/java/pl/allegro/tech/hermes/common/cache/queue/LinkedHashSetBlockingQueue.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/cache/queue/QueueTask.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/cache/zookeeper/ZookeeperCacheBase.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/cache/zookeeper/GroupsNodeCache.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/cache/zookeeper/SubscriptionsNodeCache.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/cache/zookeeper/TopicsNodeCache.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/cache/zookeeper/ZookeeperSubscriptionsCache.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/cache/topic/zookeeper/ZookeeperTopicsCache.java
1. Introduced handling of consumer commands on separate ThreadPoolExecutor that has a property of providing sequence of unique tasks (via LinkedHashSetBlockingQueue).
2. Consumer suspension doesn't wait for message TTL to expire anymore.
=> 374 separated handling of zk events from processing consumer commands

hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClient.java, hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java
Once https://github.com/schema-repo/schema-repo/pull/44 is merged, the reason for schema validation failure from schema-repo will be visible in the console.
=> providing reason when schema-repo returns 403 forbidden

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schema/repo/SchemaRepoClientFactory.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SchemaRepositoryConfiguration.java
Introduces configurable timeouts in jersey client to schema repo with reasonable defaults.
=> 395 timeouts in schema repo jersey client

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatchReceiver.java
Batch receiver is not shutdown properly which results in threads leaking
=> 413 fix for batch receiver shutdown

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchDeliveryTest.java
Hermes does not configure max number of rebalance retries for kafka consumers. Default value is 4. I have noticed that when `kafka.common.ConsumerRebalanceFailedException: ... can't rebalance after 4 retries` is thrown then some topic partitions can be blocked and messages from them are not read. 
This is one of the reason why we should migrate to 0.9 kafka-consumer. In the meantime I propose this PR which increase max number of rebalance retries and decrease backoff time between retries from 20s to 4s, consequently it should speed up kafka-consumer startup when first rebalance fails.
=> Kafka consumers rebalance

docs/docs/user/java-client.md, hermes-client/build.gradle, hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesResponse.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesResponseBuilder.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/okhttp/OkHttpHermesSender.java, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/HermesSenderTest.groovy, integration/build.gradle, integration/src/integration/java/pl/allegro/tech/hermes/integration/HermesClientPublishingTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/FrontendStarter.java
The biggest change is the HermesResponse#getProtocol() method that has been agreed with Adam. It will help Hermes users to troubleshoot switching to HTTP/2.
=> #477 | Upgrade to OkHttp Client 3.2

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoader.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducer.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/MessagePublisher.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/PublishingServlet.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/callbacks/BrokerListenersPublishingCallback.java
This is a minimalistic PR fixing memory leak problem when kafka is down.
Currently when kafka is down frontend persists all messages in backup storage. Backup storage allocates memory off heap. So it quickly can lead to no free memory on the machine. This fix does not persist messages in backup storage when there is no free space in internal kafka producer buffer. For this situation 5xx status code is returned. 
With this fix message will be only persisted in backup storage when 202 status code is returned.
=> Backup messages only for 202

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupFilesManager.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoader.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/PersistentBufferExtension.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/BrokerMessageProducer.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducer.java, hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupFilesManagerTest.java, hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoaderTest.java
PR contains two unrelated commits with separate functionality:
1. loading backup messages from multiple stale backup files
2. waiting on topic metadata before backup messages are send to kafka-producer. There is no point to send them when kafka nodes are not available in frontend startup phase, because they will not get to internal kafka producer buffer and they will not be send to kafka. Therefore safer way is to wait on broker topic metadata and after that send backup messages.
=> Stale backup files

hermes-consumers/build.gradle, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/avro/AvroPathPredicate.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/avro/AvroPathSubscriptionMessageFilterCompiler.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/filtering/AvroPathMessageFilterSpec.groovy, hermes-consumers/src/test/resources/cake.avsc
This PR removed usage of avpath library because it seems to no longer be maintained. As a replacement we have simple selector that understands paths like ".foo.bar". Matching over collections and any sort of complex querying is not supported at the moment. With that being said this filter supports all cases that we encountered in production at the moment.
=> 489 replaced avropath with simple avro filter

hermes-console/static/js/console/subscription/SubscriptionController.js, hermes-console/static/partials/subscription.html
Fixing subscription metadata visibility in the console: available metadata entries will always be visible, even when not set for subscription.
=> Subscription metadata visibility

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/FilteredMessageHandler.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/BatchConsumerRateLimiter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/ConsumerRateLimitSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/ConsumerRateLimiter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/SerialConsumerRateLimiter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/ReceiverFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerFactory.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
We rate limit sending messages, but we have no limits for filtered messages. This means that if lag on filtered subscription is high and most of the messages get filtered, we spend a lot of time reading & discarding messages. This PR adds rate limiting to filtered messages. Rate limiter is shared with sending rate limiter.
=> add rate limiting to filtered messages

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/schema/CachedCompiledSchemaRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schema/AvroCompiledSchemaRepositoryFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/schema/JsonCompiledSchemaRepositoryFactory.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/domain/topic/schema/CachedCompiledSchemaRepositoryTest.groovy
Added expire-after-access to second level schema repository cache. Main idea is that cache is self maintaining and invalidates entries that were not used for *n* minutes/hours/days. This should reduce memory footprint for our dev/test environment and also partially support workflow where user wants to  delete entire topic with all its schemas and replace it with topic with the same name. In this solution on  *topic reboot* it is required to wait until all caches invalidate. Previously we had to reset entire module to clear caches with compiled schemas.
=> 488 added expire_after_access to CachedCompiledSchemaRepository

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/CounterMatcher.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatchReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/FilteredMessageHandler.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/MessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/FilteringMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiver.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchDeliveryTest.java
Currently if Consumer spends 99.999% of its time filtering out events, it will be marked as unhealthy, as it will never process incoming signals.
This PR changes the API of `MessageResolver`, so that it communicates with `Optional<Message>` instead of throwing exceptions or spinning. If message needs to be filtered out or read timed out, `Optional.empty()` is returned.
=> process interrupts in highly filtered subscriptions

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/CacheListeners.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/HermesConsumers.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/di/ConsumersBinder.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumersSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/NonblockingConsumersSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/ConsumersRuntimeMonitor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/ConsumersRuntimeMonitorFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/DifferenceCalculator.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/SetDifference.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/RunningConsumerProcesses.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/Signal.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/mirror/MirroringSupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/SelectiveSupervisorController.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilterTest.groovy, integration/src/integration/java/pl/allegro/tech/hermes/integration/MessageBufferLoadingTest.java
This PR fixes two sources of instability of new Consumer Process model:
* consumers have graceful shutdown period - by default Consuemr has 5 minutes to shutdown before it gets killed, the rebalance timeout has been adjusted accordingly (4 minutes)
* consumers filter out unwanted signals - calling START & STOP immediately will result in no action, calling multiple updates will make only the most recent one to be applied etc
Also i added a way to monitor assignments vs real consumer processes.
=> Consumers graceful shutdown

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java
Consumers request timeout max value increased from 1 to 5 mins.
=> Subsciption request timeout max value increased to 5 min

hermes-management/src/main/java/pl/allegro/tech/hermes/management/spring/ApplicationEnvironmentPreparedEventListener.java
This PR fixes bootstrap phase check for compatible with `spring-cloud-context 1.1.0.RELEASE`.
=> Spring context bootstrap phase check fix

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
Since `ScheduledExecutorService` in `ConsumerMessageSender` is never shutdown, it might artificially keep the subscription alive, sending messages etc when there are some messages trapped in retry circle (up to TTL).
I suspect this could have caused some zombie subscriptions and hanging threads we were seeing on prod. Thanks to @samuel-beniamin for pinpointing the issue.
=> shutdown retry executor on ConsumerProcess stop

hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/consumers/ConsumersElasticsearchLogRepositoryTest.java
Tests in `ConsumersElasticsearchLogRepositoryTest` were not running. Adjusted annotations to match `FrontendElasticsearchLogRepositoryTest`, now it's fine.
=> Enables disabled consumers log repository tests

config/checkstyle/checkstyle.xml, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CachedSchemaVersionsRepository.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CouldNotFetchSchemaVersionException.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CouldNotFetchSchemaVersionsException.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CouldNotRegisterSchemaException.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CouldNotRegisterSchemaSubjectException.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClient.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClient.java, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/CachedSchemaVersionsRepositoryTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/DirectCompiledSchemaRepositoryTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClientTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClientTest.groovy
This fix changes the behaviour of schema repository clients, as they previously didn't throw proper exceptions when schema repository underneath returned server errors etc.
Cache itself works properly.
fixes #607
=> Schema versions cache fix

hermes-management/src/main/java/pl/allegro/tech/hermes/management/HermesManagement.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/CORSFilter.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/CorsConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/CorsProperties.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SupportTeamConfiguration.java
Hermes-management sets `Access-Control-Allow-Origin` header to `*` to allow AJAX requests from hermes-console. This is too broad and enables CSRF attacks on hermes-management API.
This PR makes the allowed origin configurable, so it can be narrowed to a single domain hosting the console. `*` stays as the default for backwards compatibility, we should probably rethink this before 1.0.0 release. Also removed `Access-Control-Allow-Credentials: true` as we don't use cookies in hermes-management.
=> Explicit CORS allowed domain

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageFactory.java, hermes-test-helper/src/main/resources/schema/user_no_metadata.avsc, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java
This fixes #613 bug
Now, there should be a 201 response + an exception logged, as expected:
```
2016-11-09 14:55:24.663 WARN  p.a.t.h.f.p.message.MessageFactory - Unsuccessful wrapping of AVRO message on topic jsonToAvroDryRun.topic2 in dry run mode
pl.allegro.tech.hermes.common.message.wrapper.WrappingException: Could not wrap avro message
at pl.allegro.tech.hermes.common.message.wrapper.AvroMessageContentWrapper.wrapContent(AvroMessageContentWrapper.java:64)
at pl.allegro.tech.hermes.common.message.wrapper.MessageContentWrapper.wrapAvro(MessageContentWrapper.java:75)
at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.createAvroMessage(MessageFactory.java:97)
at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.create(MessageFactory.java:62)
at …
```
=> 613 json to avro dry-run fix

hermes-common/src/main/java/pl/allegro/tech/hermes/common/admin/zookeeper/ZookeeperAdminCache.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperAdminCacheTest.groovy, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/StorageConfiguration.java
* removed deletion of zk node when handling retransmission event (this node should be cleared by reaper process in management)
* added check for not processing retransmission events that are older than java process itself
=> 630 fixed bug with retransmission node being removed before consumption

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/ConfigFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-console/static/index.html, hermes-console/static/js/console/topic/TopicController.js, hermes-console/static/js/console/topic/TopicFactory.js, hermes-console/static/js/filters/readableSize.js, hermes-console/static/partials/modal/editTopic.html, hermes-console/static/partials/topic.html, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerFactory.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/ContentLengthChecker.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/MessageReadHandler.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/TopicBuilder.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/ConsumersStarter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/FrontendStarter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java
General idea is that configuring KafkaConsumer the same for every subscription is too inefficient memory wise. This PR introduces way to specify max message size per topic which is needed to correctly configure maxPartitionFetchBytes which basically represents how heavy the buffer is per partition for receiving messages from Kafka. Goal was not to exceed 1 mb by default per subscription.
=> 655 max message size per topic

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/CuratorClientFactory.java
This PR adds conversion from seconds to milliseconds which was missing for max sleep time between zookeeper connection retries. Thanks this retries will be done between 30 seconds instead of 30 milliseconds.
=> Fixing max sleep time for zookeeper connection retries  

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Gauges.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/HermesMetrics.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/chronicle/ChronicleMapMessageRepository.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/PersistentBufferExtension.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PublishingHandler.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/TimeoutHandler.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/end/MessageEndProcessor.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/end/MessageErrorProcessor.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageState.java, hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/message/MessageStateTest.groovy
I have noticed that exceptions from backup storage can be swallowed. Therefore this PR:
- handles exceptions at the beginning of tasks which are run directly on worker thread without `Handler` layer
- reports number of messages in backup storage. This value can help us diagnose whether we have a problem with deleting messages from backup storage
- handles exceptions in few other places
Further investigation revealed corner case which was not handled during race between ack and timeout tasks. Because of it number of messages in backup storage can grow with a time. This PR fixes this problem providing additional message state `DELAYED_SENT_TO_KAFKA`
Solves #694
=> #694 Additional exception handling in hermes-frontend

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/ConsumerFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/ConsumersRuntimeMonitor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/monitor/ConsumersRuntimeMonitorFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/RunningConsumerProcesses.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignment.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentAware.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentPathSerializer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentRegistry.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentRegistryFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentView.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SupervisorControllerFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkTracker.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/mirror/MirroringSupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/BalancingJob.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/ConsumerNodesRegistry.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/SelectiveSupervisorController.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/selective/SelectiveWorkBalancer.java, hermes-consumers/src/main/resources/logback.xml, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SelectiveSupervisorControllersIntegrationTest.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SelectiveWorkBalancerTest.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/WorkTrackerTest.java, integration/build.gradle
This PR solves two issues:
- inconsistent distribution of assignments could happen when assignment cache was not built completely when workload balancing took place
- failed creations of consumers resulted in those consumer processes being missing and never re-created
In the first case, initializing the cache with existing assignments has been introduced.
The latter utilizes the running consumers monitor to issue signals for re-assigning consumers.
Edit:
During development more issues have been solved:
- inconsistent reporting by `ConsumersRuntimeMonitor` has been fixed to take a snapshot at the beginning of a run - it used the underlying structure of running processes before, which would change during the run
- when zookeeper is down, consumer would never come back to life, as it …
=> Selective algorithm healing

hermes-frontend/build.gradle
This dependency was not used, shadowed by Kafka from `hermes-common`. Still it should not be here.
Connected to #706
=> Remove ancient Kafka dependency (not used)

integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SupportTeamToOwnerMigratorIntegrationTest.java
Removes stats check in owner migration integration test. We sometimes migrate more topics than expected, because of a shared Zookeeper and Kafka containing topics from the other tests. Removing all topics before the test doesn't help, probably there is sometimes a race with previous tests adding some topics. Stats are verified in a separate unit test anyway.
=> Fixes flaky owner migration integration test

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Group.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/query/MatcherQuery.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java
Currently we don't match groups / topics / subscriptions when querying by a field that doesn't exist in a given instance. E.g. querying topics with `{"query": {"endpoint": "xxx"}}` (no topic has a field called `endpoint`) always gives an empty result.
This doesn't hold when querying by a missing nested field, e.g. `{"query": {"endpoint.nested": "xxx"}}`. In such case an exception is thrown, the query stops and the result is a 500 error response.
This PR introduces not matching entities that don't have a queried nested fields instead of failing the query with a 500 response.
=> Don't match when queried nested field doesn't exist instead of failing

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/ConsumerRateLimitSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateBalancer.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateBalancerTest.groovy
In case of negotiated max rate algorithm, if subscription rate is lower than consumer count, the algorithm could calculate a negative max rate value.
This in turn would collapse the whole rate limiting supervisor, as the iteration was stopped by a misconfigured rate limit.
=> Correcting issues caused by subscriptions with rate set to too low value

hermes-api/src/main/java/pl/allegro/tech/hermes/api/PublishingAuth.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/HandlersChainFactory.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/TopicHandler.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/auth/AuthenticationConfiguration.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/server/auth/Roles.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/TopicBuilder.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/FrontendAuthenticationConfigurationTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/SingleUserAwareIdentityManager.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/TopicAuthorisationTest.java
Added simple authorisation mechanism for publishing. It is based on service name extracted from SecurityContext. User can configure which service can publish on particular topic via **topic.auth.publishers** field.
=> introduced topic auth

hermes-api/src/main/java/pl/allegro/tech/hermes/api/AvroMediaType.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/TopicEndpoint.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/UnsupportedContentTypeException.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/ApacheHttpClientMessageBatchSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestFactory.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageContentTypeEnforcer.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageFactory.java, hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageContentTypeEnforcerTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java
Added check which accepts only "binary/avro" or "application/json" message content-type.
In other cases,  http status 400 and proper error message will be returned.
#728
=> 728 payload content-type check & error handling

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/HermesMetrics.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Timers.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/timer/StartedTimersPair.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/RawSchemaClientFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/ReadMetricsTrackingRawSchemaClient.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/SchemaRepositoryType.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/common/schema/ReadMetricsTrackingRawSchemaClientTest.groovy, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoader.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/metric/CachedTopic.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/ExchangeMetrics.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/MessageReadHandler.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PublishingHandler.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageFactory.java, hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessagesLoaderTest.java, hermes-metrics/src/main/java/pl/allegro/tech/hermes/metrics/PathContext.java, hermes-metrics/src/main/java/pl/allegro/tech/hermes/metrics/PathsCompiler.java
New metrics:
`<schema-repo-type>.latency.read-schema`
`<schema-repo-type>.latency.read-schema.group.topic`
`<schema-repo-type>.latency.get-schema-versions`
where `<schema-repo-type>` can be: `schema-repo` or `schema-registry`
#634
=> 634 added latency metrics for schema registry

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java
Ignoring Subscription status update when receiving value `PENDING`.
This resolves issue with overwriting state described in #734
Issue could happen when user created new Subscription and shortly after that edited it without reloading the console page.
After consumer initialization was finished, subscriptions state was set `ACTIVE` in zookeper, but browser still had `PENDING` value. 
At that stage, saving from console updated Subscription with `PENDING` value which caused the problem.
=> 734 prevent manual setting of subscription state to PENDING

docs/docs/configuration/rate-limiting.md, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/HierarchicalCache.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateProviderFactory.java
Prevents lost history updates when consumers are nearly busy,
which could happen when
consumer.maxrate.min.significant.update.percent / 100
was higher than consumer.maxrate.busy.tolerance.
=> Verifying configuration for negotiated max rate algorithm

hermes-api/src/main/java/pl/allegro/tech/hermes/api/AvroMediaType.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/AvroEncodedJsonAvroConverter.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageContentTypeEnforcer.java, hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/publishing/message/MessageContentTypeEnforcerTest.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/avro/AvroUser.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/HermesPublisher.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java
Added `avro/json` payload content-type and applied standard `JSON->AVRO` conversion mechanism for messages with this type. (based on https://avro.apache.org/docs/1.8.1/spec.html#json_encoding)
This addresses the issue with custom JSON converter (https://github.com/allegro/json-avro-converter/issues/14), where more complex Union types could not be properly matched, since plain JSON does not carry type information.
For given schema:
```json
{
"namespace": "pl.allegro",
"type": "record",
"name": "User",
"fields": [
{
"name": "__metadata",
"type": ["null", {"type": "map", "values": "string"}],
"default": null
},
{"name": "name", "type": "string"},
{"name": "age",  "type": "int"},
{"name": "favoriteColor", "type": ["null", "string"]}
]
}
```
proper `avro/json` formatted message is:
```json …
```
=> Handling conversion of JSON with standard Avro encoding

hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/HierarchicalCacheLevel.java
By moving Zookeeper cache logs and SchemaRegistry logs (#750) to debug, we can reduce number of log messages by almost 100x. I think those logs are of little value for us and only make it harder to actually debug issues with Hermes.
Before:
After:
=> Move Zookeeper cache logs to debug to decrease log noise

hermes-api/src/main/java/pl/allegro/tech/hermes/api/MessageTextPreview.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/preview/MessagePreview.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/preview/MessagePreviewRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/preview/TopicsMessagesPreview.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperMessagePreviewRepository.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperMessagePreviewRepositoryTest.groovy, hermes-console/static/css/main.css, hermes-console/static/partials/topic.html, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/FrontendBinder.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewFactory.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewLog.java, hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewFactoryTest.groovy, hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewLogTest.groovy, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java
Message preview will be truncated in `MessagePreviewLog#add` if its size exceeds limit defined in `Configs.FRONTEND_MESSAGE_PREVIEW_MAX_SIZE_KB` (10 by default). Additionally to preview content, a `truncated` flag will be stored in Zookeeper for later display in "Topic message preview" panel:
Previews already stored in ZK (flat structure, only preview content) are not supported, meaning that they won't be displayed. Once new messages arrive, they will be stored in new format and older ones should be discarded.
=> Limit size of messages in preview #710

docs/docs/deployment/deployment.md
because the existing documentation was causing "Unrecognized option" error
=> Update doc on setting Env Variable for Management

hermes-console/static/css/main.css, hermes-console/static/index.html
This small change is related to #692 and improves the toaster notification widget of the console as follows:
* notification box will resize according to body text (with maximum size of 800px) - currently it was 300px fixed, so longer error messages were hard to read
* error messages require user interaction in order to disappear - close button is shown
=> Console notification box UX improvements

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisorTest.groovy
Signals for `ConsumerProcessSupervisor` are produced from few threads on a single queue. These threads are not synchronized with each other which means that signals can be mixed on the queue.
Next, signals are consumed in batches by a single thread. Single batch can contain mixed sequence of signals like so:
```
1. CLEAN - from some STOP signal
2. COMMIT - from commit thread
``` 
At the moment, `ConsumerProcessSupervisor` verifies whether consumer process exists only at the beginning of a batch process. However, some signals from the batch can remove consumer process and next signals from this batch can end up with NPE as consumer process was not found.
This PR fixes described problem by verifying whether consumer process exists for each processed signal.
This is a first step to solve …
=> Ensuring that consumer process exists for processed signal

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java
Reinitialize message receiver when schemaVersionAwareSerialization flag on topic is updated. Without this feature subscription had to be suspended and activated manually. 
This is an additional fix to #779
=> Message receiver reinitialization after schemaVersionAwareSerialization update

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterStorage.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepository.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepositoryTest.groovy, hermes-common/src/test/groovy/pl/allegro/tech/hermes/test/IntegrationTest.groovy, hermes-common/src/test/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterStorageTest.java
There is validation on topic removal that there are no subscriptions on
that topic. But in the same time the metric which has subpath same as
subscription path is stored (e.g. subscription path is
/groups/{group}/topics/{topic}/subscriptions/{sub} and metric path is
/groups/{group}/topics/{topic}/subscriptions/{sub}/metrics/delivered
Validation checks only if path exists.
The situation when there were no subscription but metric was stored
may be caused by missing subscription check while storing inflight
counter or because of the race condition (removing topic and storing
metric at the same time).
The solution is to check if data for subscription path is actually
present and also to add missing check.
=> #780 Fixed problem with topic removal due to metrics

hermes-console/static/js/console/subscription/SubscriptionController.js
Attempt to select starting date for messages retransmission (subscription management screen) ends up with JS console errors. Bug introduced [here](https://github.com/allegro/hermes/commit/49df75281cfa81c236504dc8ec7e95d1ca5e6e1a#diff-dde55599949256892447ffd2141c45b4L41).
=> Fixed retransmission bug in hermes-console

.gitignore, hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetentionTime.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/PublishingAuth.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicDataOfflineStorage.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicWithSchema.java, hermes-console/static/js/console/topic/TopicFactory.js, hermes-console/static/partials/modal/editTopic.html, hermes-console/static/partials/topic.html, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/TopicBuilder.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java, vagrant_provisioning/install_kafka.sh
Offline storage metadata are not actually used in Hermes, but they can signal if systems like Goblin or Camus should dump data from underlying Kafka topic onto offline store (e.g. HDFS)
=> Add offline store information

.travis.yml, hermes-benchmark/build.gradle, integration/build.gradle
Removed caching because it basically doesn't work.
=> Splits unit, integration and JMH tests into separate, parallel builds on Travis

hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/AvroCompiledSchemaRepositoryFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/SchemaVersionsRepositoryFactory.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CachedCompiledSchemaRepository.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/CachedSchemaVersionsRepository.java, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/CachedCompiledSchemaRepositoryTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/CachedSchemaVersionsRepositoryTest.groovy
Fixes #811
I haven't included integrations tests, because Confluent Schema Registry does not allow to remove schema. I would have to mock rawClient which is already done in unit tests.
=> Clean schema cache on topic removal

hermes-console/static/partials/modal/editSubscription.html
There was a difference in subscription name regexp between `hermes-console` nad `hermes-management`, so subscriptions with `_` in the name created via hermes http api could not be edited through console, as the name was invalid.
=> Console subscription name regexp fix

hermes-api/src/main/java/pl/allegro/tech/hermes/api/BatchSubscriptionPolicy.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchDeliveryTest.java
User supplied ttl in seconds but we expected milliseconds.
=> fixed bug with time conversion when reading message_ttl for batch sub

hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SchemaRepositoryConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SchemaRepositoryProperties.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryCompatibilityResponse.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClient.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryValidationError.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryValidationResponse.java, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClientTest.groovy
Adding support for custom schema-registry validation endpoint. The endpoint is disabled by default as it is not in official schema-registry Confluent API.
Solves #767
=> Supporting schema-registry validation endpoint

hermes-frontend/build.gradle
Fixes a possible deadlock in `io.undertow.protocols.http2.Http2Channel` that we observed recently. See https://issues.jboss.org/browse/UNDERTOW-1231.
=> Updates Undertow to 1.4.21.Final (deadlock fix)

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/exception/RetransmissionException.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/message/wrapper/MessageContentWrapper.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/kafka/broker/KafkaConsumerOffsetMover.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/kafka/broker/PartitionAssigningAwareRetransmitter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/kafka/broker/PartitionNotAssignedException.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/offset/kafka/broker/PartitionAssigningAwareRetransmitterTest.groovy, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClient.java
There is an issue that we're not sending some portion of events when migrating from json to avro.
Events not being sent to subscriber:
- last events from json topic
- initial events from avro topic
Causes:
- issue with trying to deserialize json event with avro schema (wrong content type used when unwrapping event read from kafka)
- retransmission after migration was happening before consumer had any partition assigned from kafka which resulted in failed retransmission
=> fixed bug with some portion of events not being sent during migration from json to avro

hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperPaths.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateRegistry.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentCache.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/MaxRateRegistryTest.java, integration/src/test/resources/config.properties
Lazy loading of MaxRateRegistry's Zookeeper cache can take a very long time. Eagerly initializing the tree should significantly speed up start time of Hermes Consumers.
More improvements can be made, but this one is the low hanging fruit we ought to consider.
=> Consumers maxrate eager start

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/NonblockingConsumersSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/RunningConsumerProcesses.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisorTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessTest.groovy, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SelectiveSupervisorControllersIntegrationTest.java
This pull request improves consumer's resource managing performed by process supervisor. It tries to resolve multiple problems caused by consumer's resources shared between multiple threads. One of the problem is ConcurrentModificationException on KafkaConsumer object which is not thread safe. The error is caused due to connection problems with Kafka cluster. When ConsumerProcess cannot connect to Kafka it is assumed as unhealthy and is supposed to be restarted. After continuous restarting some corner cases cause to spawn multiple threads (ConsumerProcesses) operating on the same KafkaConsumer object. The fix works by creating new KafkaConsumer object for each spawned ConsumerProcess (previously it was just passed to newly created process in case of restart).
Changes made: …
=> Eliminating consumer's resources sharing between multiple processes

hermes-api/src/main/java/pl/allegro/tech/hermes/api/endpoints/TopicEndpoint.java, hermes-common/src/main/java/pl/allegro/tech/hermes/domain/topic/TopicRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepository.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepositoryTest.groovy, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicOwnerCache.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java, hermes-management/src/main/resources/application.yaml, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/ListTopicForOwnerTest.java, integration/src/test/resources/application-integration.yaml
We want to be able to list topics by owners. We can do this right now by using `QueryEndpoint`, but quering requires scanning through whole Zookeeper, which is too slow (something about 1 to 15 seconds on production).
Another reason that seperate endpoint is better is that we can change response structure. We may also add list subscriptions for topics.
I built cache from `OwnerId` to `TopicName` which is filled after application startup. Then every CRUD operation on topic updates the cache.
I created seperate class that is used by `TopicService`. I considered implementing existing `Audit` interface and inject `List<Audit>` instead of `Audit` so that `TopicService` would not know about cache, but I feel like `Audit` and `Cache` is a different thing. Moreover, Audit methods are called by …
=> List topics by owners

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Timers.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/idleTime/ExponentiallyGrowingIdleTimeCalculator.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/idleTime/IdleTimeCalculator.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/ThrottlingMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/ExponentiallyGrowingIdleTimeCalculatorTest.groovy
Added waiting between unsuccessful polls to reduce cpu utilization. Right now call to`kafkaConsumer.poll(timeout)` is very cpu intensive because KafkaConsumer implementation is constantly looping until timeout is reached. I used simple exponentially growing waiting strategy.
=> added waiting between unsuccessful polls to reduce cpu utilization

docs/docs/user/subscribing.md, hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java, hermes-console/static/js/console/subscription/SubscriptionFactory.js, hermes-console/static/partials/modal/editSubscription.html, hermes-console/static/partials/subscription.html, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringJsonTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java
This PR implements feature of delayed events. We want to give users possibility to postpone sending an event for given time (max 5 seconds) so if there are multiple topics that sends messages at the same time, then can increase chance of receiving an event from one topic before an event from another topic.
I implemented this feature in serial subscriptions. It will require more code and testing to support batch subscriptions. I believe that clients that asked about this feature use serial subscriptions. We can always support batches in a separate PR.
=> Sending delay

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/BackupMessage.java
This change is needed for a migration tool before a  #893
=> make BackupMessage serializable

hermes-console/static/partials/modal/editSubscription.html
Sending delay should not be required in batch subscription. Right now, it blocks batch subscription editing.
=> Sending Delay is not required in batch subscription

integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java
Test for checking if headers are case-insensitive.
=> Test case for lowercase header

build.gradle, hermes-client/build.gradle, hermes-consumers/build.gradle, hermes-management/build.gradle, hermes-mock/build.gradle, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClientTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClientTest.groovy, hermes-test-helper/build.gradle, integration/src/integration/java/pl/allegro/tech/hermes/integration/BatchRetryPolicyTest.java
Updating wiremock to the latest version (2.19.0) and using standalone version where it is possible to avoid conflicts of its dependencies. Solves #804
=> Updating wiremock

.travis.yml, integration/build.gradle
Fixing integration tests by:
1. Defining APLN version for the latest update of java 8
2. Running integration tests on the default travis infrastructure by remove of `sudo: false` rule from `travis.yaml` file. Tests are passing now. Maybe this is related to the travis infrastructure changes described in this [post](https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures).
Info about random container from travis-ci. It contains 24CPU units, however load on it is around **60.0**. According to [this](http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages) article when the load is higher than a number of cores then we can be in a serious trouble as the container is either hanging or slowing way down. We have to move our integration tests to a different host or …
=> Fixing integration tests

hermes-tracker-elasticsearch/src/main/java/pl/allegro/tech/hermes/tracker/elasticsearch/SchemaManager.java, hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/consumers/ConsumersElasticsearchLogRepositoryTest.java, hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/frontend/FrontendElasticsearchLogRepositoryTest.java, hermes-tracker-elasticsearch/src/test/java/pl/allegro/tech/hermes/tracker/elasticsearch/management/ElasticsearchLogRepositoryTest.java, hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/frontend/AbstractLogRepositoryTest.java
Changes for elasticsearch template mapping.
1. Converting timestamp fields to `date` type. Thanks to this it will be easier to search documents from kibana.
2. Indexing `timestamp_seconds` but not `timestamp` field (which has values in milliseconds). Related to [performance](https://engineering.mixmax.com/blog/30x-faster-elasticsearch-queries) improvement.
3. Disabling [norms](https://www.elastic.co/guide/en/elasticsearch/reference/current/norms.html) feature for text fields. Related to disk usage optimization.
=> Optimizing elasticsearch template mapping

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/executor/InstrumentedExecutorServiceFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/ModelAwareZookeeperNotifyingCache.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/oauth/OAuthProvidersNotifyingCacheFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/oauth/OAuthSubscriptionHandler.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/message/undelivered/UndeliveredMessageLogPersister.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/SubscriptionAssignmentCache.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/preview/MessagePreviewPersister.java
There were some unnamed thread pools left in code (in consumers module mostly). Naming them should help in thread dump analysis.
=> Giving names to all anonymous thread pools

hermes-management/src/main/resources/application.yaml, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/HealthCheckTest.java, integration/src/test/resources/application.yaml
Bringing back to live `/status/health` endpoint in hermes-management after spring-boot dependency upgrade. Issue related to #993
=> Enabled /status/health endpoint in hermes-management

hermes-console/static/partials/topic.html, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/clients/OfflineClient.java
We would like to add additional field `owners` in offline clients feature. This field can contain list of owners for technical user.
Here is a screen how it can look for our internal implementation of offline clients feature:
=> Extending offline clients by 'owners' field

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java
I've moved the `is-running` check to upper level, so none of the message sending handlers will be triggered  when the consumer is being closed.
resolves #1026, resolves #623
=> Message sending handlers triggered only when consumer is running

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitter.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetQueue.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/queue/FullDrainMpscQueue.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/queue/MonitoredMpscQueue.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/queue/MpscQueue.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/queue/WaitFreeDrainMpscQueue.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcessSupervisor.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilter.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/SignalsFilterTest.groovy, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/queue/FullDrainMpscQueueTest.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/queue/MpscQueuesAbstractTest.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/queue/WaitFreeDrainMpscQueueTest.java, integration/src/test/resources/config.properties
This change introduces an alternative approach to draining MpscQueue used as inflight offsets storage. The default `drain()` would possibly skip some items due to [broken chain when multiple producers race when offering new items](http://psy-lob-saw.blogspot.com/2014/07/poll-me-maybe.html).
Draining the inflight offsets queue only partially could end in changing the order as offsets become available (committed offset is available, but inflight is not) - see [comment](https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitter.java#L100) - meaning we can't progress in committing offsets for partition.
=> Full drain MpscQueue

.travis.yml
After yet another
```
Could not GET 'https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.9.4/jackson-annotations-2.9.4.pom'. Received status code 403 from server: Forbidden
```
I've decided to enable Maven and Gradle caching
=> Enable caching for dependencies on Travis

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java
While stopping consumer process there might be an exception thrown by underlying kafka consumer which is not catched and logged anywhere. 
This exception as a consequence will cause `dyingConsumerProcesses.remove(subscriptionName);` not be called at all - so we have a process dying forever and we will not be able to start another one for particular subscription without a jvm restart.
=> Catch exceptions thrown while stopping kafka consumers

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitter.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/offset/OffsetCommitterTest.groovy
In our current approach the only state of `OffsetCommitter` that has been persisted for the use of upcoming algorithm runs were `inflightOffsets` that were used for preventing from skipping some messages that were currently inflight.
Turns out we should store maximum possible offsets as well. 
Imagine such scenario (just as in added test case):
* We have a partition with messages with offsets 1 and 2
* Consumer sends the messages:
* message with offset=2 is delivered immediately
* message with offset=1 is being retried for an hour and eventually discarded
* Before message with offset=1 is discarded the `OffsetCommitter` algorithm runs and loses the information about message with offset=2 being delivered (it remembers only offset=1 as the one that is still inflight at the time)
* No new …
=> Maximum possible offset to be committed for partition

hermes-common/src/main/java/pl/allegro/tech/hermes/domain/subscription/SubscriptionAlreadyExistsException.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/validator/SubscriptionValidator.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java
One of Hermes users discovered that when we click on a `Clone` button on a subscription view, next save copied subscription without changing it’s name then the subscription is removed. The problem is related to rollback policy in `CreateSubscriptionRepositoryCommand`. To solve it I’ve added additional check for subscription existence before `CreateSubscriptionRepositoryCommand` is executed. Topic creation already have this kind of check.
=> Added check for subscription existence during it’s creation

hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockHelper.java, hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockAvroTest.groovy, hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockTest.groovy
I found that response from `wireMockServer.stubFor` was never verified in test, so I also added status code verification to base tests in `HermesMockAvroTest` and `HermesMockTest`.
This was mostly done to ensure that `WireMock` still matches request after addition of `.withHeader("Content-Type", equalTo(contentType))`.
=> #1093 hermes-mock matches content-type header

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/workload/FlatBinaryClusterAssignmentCache.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/FlatBinaryWorkloadRegistryTest.java
Cluster assignment cache wasn't properly cleared from previous assignments, and it could create some mess and cause rebalance job to behave unstable.
=> Remove stale assignments from cluster assignment cache

hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/rate/maxrate/HierarchicalCacheMaxRateRegistryTest.java
Fix for zookeeper callback related tests that could be flaky on CI.
=> Hierarchical max rate registry test fix

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/id/NotificationAwareSubscriptionIdsCache.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/subscription/id/SubscriptionIdsCacheFactory.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/subscription/id/NotificationAwareSubscriptionIdsCacheTest.groovy, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/supervisor/workload/ConsumerTestRuntimeEnvironment.java
resolves #1145 
Ids of removed subscriptions should be still available for some time after the subscriptions are removed, due to the way selective workload algorithm works (it decodes them and should not filter them out in order to clean the mess properly). I'm introducing cache for removed subscriptions that is cleared after some specified time of inactivity (should be bigger than configured intervals for workload/max-rate computations).
=> Subscription ids cache removed expire after specified time

hermes-console/static/js/bootstrap.js
When using console in IE, because js in IE does not support endswith() , hermes-console does not load properly.
=> add support for IE 11

hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockExpect.java, hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockAvroTest.groovy, hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockTest.groovy
The problem lies in `HermesMockExpect.assertMessages`.
`expectMessages` and `expectSpecificMessages` are orthogonal, 'cause they assert different behaviour, total number of events vs specific events respectively.
Such behaviour was caused by a too generic predicate in tests.
Fixes #1152
=> Fix Hermes mock predicate

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicWithSchema.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepository.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepository.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionRepositoryTest.groovy, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperTopicRepositoryTest.groovy, hermes-console/static/js/console/subscription/SubscriptionController.js, hermes-console/static/js/console/topic/TopicController.js, hermes-console/static/partials/subscription.html, hermes-console/static/partials/topic.html, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/TopicBuilder.java
#1123 
For now I implemented it only for subscription. Please check it out and give me a feedback, then I will continue working.
What format of creation and modification date do you expect? Timestamp (`Long`) or human-readable string ("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")?
=> Expose creation and modification date for subscription

hermes-console/static/partials/constraints.html
Adding link to the exact topic/subscription is impossible as the whole row acts as a trigger for modal. For now the only solution is to wrap topic/subscription name with a link, but I think it would be not intuitive.
If you still want this behavior I can update PR.
=> resolves #1116 | Add sorting by name and search for constraints UI

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerProcess.java
Changing `Exception` to `Throwable` so we log not only exceptions but all other errors, including OOM that could be thrown somewhere.
=> Catching all Throwables when consuming messages

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderFactory.java, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
Currently Hermes schedules message send to a subscriber for every message even if it’s older than a `sendingDelay` value on a subscription. This PR introduces an optimization in which `delay` value is calculated for every message and is based on publishing message timestamp. Thanks to this not all messages will be delayed but only those which are younger than subscription `sendingDelay` value.
=> Sending delay is calculated based on message publishing timestamp

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/EmptyHttpHeadersProvidersFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpHeadersProvidersFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestData.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpRequestFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyHttpMessageSenderProvider.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSender.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/AuthHeadersProvider.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/HermesHeadersProvider.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/Http1HeadersProvider.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/Http2HeadersProvider.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/HttpHeadersProvider.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/HttpRequestHeaders.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/ResolvableEndpointAddress.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/resolver/SimpleEndpointAddressResolver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/di/ConsumersBinder.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSenderTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/AuthHeadersProviderTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/HermesHeadersProviderTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/Http1HermesHeadersProviderTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/Http2HermesHeadersProviderTest.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/TestHttpRequestData.groovy, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/headers/TestUris.groovy, hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageSenderTest.java
At the moment there is no way to add additional headers to consumer messages to subscribers without hacking and slashing.
This PR allows specifying additional header providers to be used by consumer during message request creation. 
Other than that, each provider can now use raw (not-yet-resolved-by-address-resolvers) address to be used when resolving such additional headers.
That can be useful in a scenario when one want to send headers like `Host` or other that rely on the information stored in the address.
=> HttpClients can have additional headers set

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/HttpClientsFactory.java
Http1/2 clients can have max requests queued per destination configured apart from consumer inflight size.
=> Max requests queued per destination config param for http clients

hermes-management/build.gradle, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/schema/SchemaService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/schema/validator/AvroSchemaValidator.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/schema/validator/InvalidSchemaException.java, hermes-management/src/main/resources/avro-schema-metadata-field.avsc, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/infrastructure/schema/validator/AvroSchemaValidatorTest.groovy, hermes-test-helper/src/main/resources/schema/user_metadata_with_avro_java_string.avsc, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingAvroTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SchemaManagementTest.java
References #1015 
Hermes Management does not allow to save topic with an invalid Avro schemas:
- schema without field `__metadata`
- schema with field `__metadata` that declares types other than hermes specifies in documentation, for example `java.avro.string`
=> Management: Schema __metadata field validation

docs/docs/user/java-client.md
Hi there!
I've found and fixed some typo but cannot see a ```develop``` branch as mentioned [here](https://github.com/allegro/hermes/blob/master/CONTRIBUTING.md) so ```master``` seems to be good one for such a small change :)
=> Fix typo in docs

hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockHelper.java
hermes-mock does not propaget root cause exception for deserailization problems. This is problematic when debugging any problems with `HermesMock.query()` module, because what I get with Avro is:
```
hermesMock.query().lastAvroMessageAs(topicName, schema, SomeClass)
pl.allegro.tech.hermes.mock.HermesMockException: Cannot read body [B@34770920 as SomeClass
```
To be able to find the real problem I need to use debugger and find root exception. This PR adds root cause to `HermesMockException`.
=> Adds deserialization root cause exception in Hermes-mock

docs/docs/configuration/consumers-tuning.md
The adoption of Hermes is still growing so I think the documentation of workload constraints will be useful for new users.
=> Add missing documentation of workload constraints

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Counters.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/FilteredMessageHandler.java
Removed duplicated counter for filtered messages. We already have `meter` for filtered messages which also contains counter, therefore we don’t need second counter for the same operation.
=> Resolve #1164 | Removed duplicated counter for filtered messages

hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/ModeEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/health/HealthCheckTask.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/mode/ModeService.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/health/HealthCheckTaskTest.groovy
Read only mode set by admin (READ_ONLY_ADMIN) in hermes management is not overwritten by healthcheck task.
=> Resolve #1211 | Read only mode persistence

hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMock.java
It is required to use annotations like @JsonCreator / @JsonProperty for classes written in kotlin. Using jackson-module-kotlin does not help, because it is not registered by default to object mapper used by HermesMockRule. 
Adding this small change fixes problem with redundant jackson annotations, and probably also a few other problems (I guess i.e. with dates conversion).   
Any idea, to test for this change?
=> hermes-mock: adding modules find and register by default

integration/build.gradle
WIP: Removing APLN for jdk 1.8.0_252. More info here: https://webtide.com/jetty-alpn-java-8u252/
=> Remove ALPN for jdk 1.8.0_252+

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/kafka/JsonToAvroMigrationKafkaNamesMapper.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/kafka/KafkaNamesMapperFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/kafka/NamespaceKafkaNamesMapper.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/schema/RawSchemaClientFactory.java, hermes-frontend/src/test/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaBrokerMessageProducerTest.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/SchemaRepositoryConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/kafka/KafkaClustersProperties.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/kafka/MultipleDcKafkaNamesMappersFactory.java, hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SubjectNamingStrategy.java, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/SubjectNamingStrategyTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/confluent/SchemaRegistryRawSchemaClientTest.groovy, hermes-schema/src/test/groovy/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClientTest.groovy, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/BrokerOperations.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/IntegrationTestKafkaNamesMapperFactory.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/Waiter.java
In #1209 I have made a mistake.
I used `.` as a namespace separator, because it is the way we define namespaces in our project, but I did not notice that the separator for namespaces on Kafka is `_`. It works, as for Hermes alone, but it is inconsistent a causes us some problems.
In this PR I have made the separator configurable.
=> configurable namespace separator

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicWithSchema.java, hermes-api/src/test/java/pl/allegro/tech/hermes/api/TopicTest.java, hermes-console/static/partials/topic.html, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/TopicProperties.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java, hermes-management/src/test/resources/application.yaml
- Add management flag `defaultSchemaIdAwareSerializationEnabled` at TopicProperties for default behavior topic in case when we don't send `schemaIdAwareSerializationEnabled`. 
- Add displaying information about `schemaIdAwareSerializationEnabled` at FE Console.
=> Feature: default schema id serialization

hermes-console/config.json.example, hermes-console/config_default.json, hermes-console/static/js/console/subscription/SubscriptionController.js, hermes-console/static/partials/modal/editSubscription.html, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java, hermes-management/src/main/resources/application-local.yaml, hermes-management/src/main/resources/console/config-local.json
- delivery types in hermes console are now read from configuration
- serial delivery cannot be changed to batch delivery
- bonus: bug fix for maxBackoffInterval field (the field is now not required for constant backoff policy)
=> Batch subscription disabled in hermes console

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/ObjectMapperFactory.java, hermes-common/src/test/java/pl/allegro/tech/hermes/common/di/ObjectMapperFactoryTest.java
Fix for issue [Serialization with Schema Id](https://github.com/allegro/hermes/pull/1232).
- injectableValues added to object mapper factory
- schema id serialization parameter added to frontend and consumers configs
=> Fix serialization with schema id

hermes-console/static/partials/modal/editSubscription.html
- subscription name cannot contain '_'
- (old) subscription with invalid name can be edited (bug fixed)
=> Subscription name validation fixed

README.md
Hi @adamdubiel  @druminski 
We've put together the first version of the demo badge so that your users can get a temporary Hermes env for poking around!
Everything seems to boot fine but I was getting some 404's. I'm not sure if that's because I was just using Hermes wrong, or if something isn't working.
Either way, would appreciate your feedback! Was this what you guys were imagining? What do you guys think?
=> Add instructions for demo

hermes-console/package.sh
hermes-console/package.sh didn't work on macOS - nodejs distro was hardcoded to linux. Thanks to this change, script will now detect darvin (macOS) based on uname output or fall back to linux for any other distro.
=> support for Darvin (macOS) in hermes-console package.sh

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Subscription.java
Hello, 
Following the CI failure on #1271, I found that the Subscription::anonymize method was not null safe so here is a fixing PR for this problem.
See https://travis-ci.org/github/allegro/hermes/builds/732064554
=> Fix possible NPE for Subscription::anonymize

build.gradle, hermes-test-helper/build.gradle
Downgraded used kafka dependencies to 2.1.1 due to specific bug occurring with pre 2.4 brokers.
=> Downgraded kafka to 2.1.1

hermes-console/static/js/console/subscription/SubscriptionController.js, hermes-console/static/js/console/topic/TopicController.js, hermes-console/static/partials/modal/editSubscription.html, hermes-console/static/partials/subscription.html
Solves #1255 .
There was a pane in subscription view and edit panel that enabled user to check and modify the header filters for that subscription. In reality, despite what the labels said, setting those filters would instead set fixed header values for those subscriptions. 
This PR addresses the issue and instead enables user to set fixed header values explicitly.
=> Fixed http headers now have a dedicated pane in console.

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/Auditor.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/audit/LoggingAuditor.java
Hello, 
This PR references issue #1267 Audit logs for unsuccessful topic and subscription operations
As discussed in this issue:
- I added beforeObjectX methods to Auditor (default to no-op)
- I implemented those methods in LoggingAuditor following the same log format when possible
- I added calls to those methods in TopicService and SubscriptionService il all methods that already logged the success
- I rearranged a bit of code around the beforeObjectUpdate calls for it to be the earliest possible (especially updateSubscriptionState)
=> resolve #1267 | Audit logs for unsuccessful topic and subscription operations

hermes-consumers/src/test/java/pl/allegro/tech/hermes/consumers/consumer/ConsumerMessageSenderTest.java
There is a test in Hermes tests that checks if sending delay works as intended. Unfortunately from time to time it doesn't pass, because the code is too fast:
`pl.allegro.tech.hermes.consumers.consumer.ConsumerMessageSenderTest > shouldDelaySendingMessageForHalfSecond FAILED
java.lang.AssertionError: 
Expecting:
<500L>
to be greater than:
<500L> 
at pl.allegro.tech.hermes.consumers.consumer.ConsumerMessageSenderTest.shouldDelaySendingMessageForHalfSecond(ConsumerMessageSenderTest.java:400)`
This PR should address this issue.
=> Fixed one test that wasn't passing from time to time

hermes-console/static/js/console/topic/TopicController.js, hermes-console/static/partials/topic.html
Adds "Copy to clipboard" button on `Message schema` bar in topic view.
=> resolve #1279 | copy message schema to clipboard

hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ConsistencyCheckerProperties.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/consistency/ConsistencyService.java, hermes-management/src/main/resources/application.yaml, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/consistency/ConsistencyServiceSpec.groovy
Thanks this PR there is no need to provide additional configuration related to `consistency checker` when running custom Hermes.
=> Moved 'consistency checker' config to Properties class

hermes-client/src/main/java/pl/allegro/tech/hermes/client/HermesClient.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/MessageDeliveryListener.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/metrics/MetricsMessageDeliveryListener.java, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/HermesClientMetricsTest.groovy
Currently metrics provided by MetricsMessageDeliveryListener might be
confusing due to poor naming and the fact that only transport layer
errors are considered a "failure".
New metrics take into account also application level errors which
are represented by http status codes. Following metrics have been
added:
- topic.publish.finally.success:
Message has been accepted by Hermes
- topic.publish.finally.failure
Message has been rejected by Hermes or there was transport level issue. Whole publish
operation is considered atomic so intermittent failures handled by retries will not
be counted by this metric.
- topic.publish.failure:
Counts number of failures including retries.
- topic.publish.attempts:
Counts number of publish attempt. Does not include retries.
- topic.publish.retry.success: …
=> Add new meaningful metrics to MetricsMessageDeliveryListener

README.md
Unfortunately, we're shutting down Blimp. This commit removes references
to Blimp to prevent broken links when it shuts down.
Thanks for trying out the badge while it was available! Let me know if you have any questions.
=> Remove demo badge

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/HermesFrontend.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/di/LoggerConfiguration.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/TopicHandler.java
This PR is related to default undertow response status [Issue](https://github.com/allegro/hermes/issues/1294)
We decided to set a 500 status code at the beginning of an exchange processing. But in consequence, Undertow logged exception for every request (related to setStatusCode method implementation). To avoid a lot of unnecessary logs we changed the logging level for an Undertow's response error logger.
=> hermes-frontend change default response http status

hermes-client/build.gradle, hermes-client/src/main/java/pl/allegro/tech/hermes/client/ReactiveHermesClient.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/ReactiveHermesClientBuilder.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/ReactiveHermesSender.java, hermes-client/src/main/java/pl/allegro/tech/hermes/client/webclient/WebClientHermesSender.java, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/ReactiveHermesClientMetricsTest.groovy, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/ReactiveHermesClientMicrometerMetricsTest.groovy, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/ReactiveHermesClientTest.groovy, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/ReactiveHermesSenderTest.groovy
This PR introduces a `ReactiveHermesClient` class and a `ReactiveHermesSender` interface implemented using `WebClient`. Both `ReactiveHermesClient` and `ReactiveHermesSender` mimic their non-reactive counterparts' API and behaviour.  Also, the reactive classes' tests are almost identical to the non-reactive classes' tests.
=> Introduce Reactive Hermes Client

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/metadata/DefaultHeadersPropagator.java, hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/publishing/metadata/DefaultHeadersPropagatorTest.groovy
After this change it's possible to enable header propagation and define which headers should be propagated
frontend.header.propagation.enabled=true
frontend.header.propagation.allow.filter=traceparent
=> Allow header propagation just by using configuration

hermes-console/static/js/console/Groups.js, hermes-console/static/js/console/subscription/SubscriptionController.js, hermes-console/static/js/console/topic/TopicController.js, hermes-console/static/partials/subscription.html
This PR reworks how we try to prevent clearing unsaved changes in Hermes-console. It should help to avoid bugs like the one we noticed recently: the state of the edited subscription wasn't propagated correctly and it was impossible to update some fields e.g. `endpoint`.
=> Prevent closing unsaved modals

hermes-client/src/main/java/pl/allegro/tech/hermes/client/metrics/MicrometerMetricsProvider.java, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/HermesClientMicrometerMetricsTest.groovy, hermes-client/src/test/groovy/pl/allegro/tech/hermes/client/ReactiveHermesClientMicrometerMetricsTest.groovy
We would like to make it possible to configure on `MeterRegistry` level if [client-side percentiles](https://micrometer.io/docs/concepts#_histograms_and_percentiles) are published. The main reason is that some implementations of `MeterRegistry` don't properly handle the property set by `io.micrometer.core.instrument.DistributionSummary.Builder#publishPercentiles`. Apart from that, as sending percentiles to the monitoring system generates additional time series, it is better to let the client decide which ones are useful.
=> hermes-client: allow configuring percentiles on MeterRegistry level

hermes-common/src/main/java/pl/allegro/tech/hermes/common/config/Configs.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/CommonBinder.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/MetricRegistryFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/PathsCompilerFactory.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/util/InetAddressInstanceIdResolver.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/util/InstanceIdResolver.java, hermes-common/src/test/java/pl/allegro/tech/hermes/common/metric/counter/zookeeper/ZookeeperCounterReporterTest.java
In this PR I renamed interface `pl.allegro.tech.hermes.common.util.HostnameResolver` to `pl.allegro.tech.hermes.common.util.InstanceIdResolver`. This adds more flexibility to the provided implementation which does not currently need to be hostname based.
=> Renamed HostnameResolver to InstanceIdResolver

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/Gauges.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/Producers.java
We need a metric recorded at the moment when kafka-producer stops sending message to broker (because of its retry policy exhausted or any other case). This message will be stored in backup storage but not be retried anymore until hermes restart.
=> Add kafka producer publishing error metrics

hermes-console/static/index.html, hermes-console/static/js/console/filters/FiltersDebugger.js, hermes-console/static/js/console/filters/FiltersEditor.js, hermes-console/static/js/console/filters/HttpHeaderFiltersEditor.js, hermes-console/static/js/console/subscription/SubscriptionController.js, hermes-console/static/partials/filter/filtersEditor.html, hermes-console/static/partials/filter/httpHeaderFiltersEditor.html, hermes-console/static/partials/modal/editSubscription.html, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/FilteringConfiguration.java, hermes-management/src/main/resources/application-local.yaml
Added `Http header filter` panel in subscription view. The panel is displayed below `Filter` panel as in the attached image. By default `Http header panel` is disabled. It can be enabled by `showHeadersFilter` flag in Hermes console config. At the moment the panel dosen't support `Debug` mode and `matching strategy`, but they can be added in the future.
=> Added UI panel for http header filters

hermes-console/static/js/console/subscription/SubscriptionFactory.js, hermes-console/static/js/console/topic/TopicFactory.js, hermes-console/static/partials/modal/editSubscription.html, hermes-console/static/partials/subscription.html, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/console/ConsoleProperties.java, hermes-management/src/main/resources/application.yaml, hermes-management/src/main/resources/console/config-local.json, hermes-management/src/main/resources/console/config-vagrant.json
This PR exposes Http client request timeout in subscription view of Hermes UI. It also displays warning when request timeout is set to a bigger value. 
Additionally, the PR changes default value of `store offline` property on topic view to `false`.
This PR is a continuation of #1327 by @tadamcze, thanks for the contribution :)
=> Configurable request timeout in subscription view. 

.github/workflows/gradle.yml, hermes-benchmark/build.gradle, hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/BenchmarkZookeeperStarter.java, hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/FrontendEnvironment.java, hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/environment/InMemorySchemaClient.java
migration to GitHub Actions allowed to detect the problems such as:
- fixed ports
- outdated `InMemorySchemaClient` class
- problems with not created Zookeeper Nodes
=> Benchmarks refactor

hermes-console/serve.js
Hermes-console doesn't work when served by NodeJS. 
You can properly serve it using hermes-management, but existing scripts (`hermes-console/serve.js`, `hermes-console/run.sh`) should be usable. 
https://github.com/allegro/hermes/blob/fa416ab9f0c6711a1f443e76e23d38fd225cd696/hermes-console/static/index.html#L30
expects configuration at `/console`, but `serve.js` expose configuration at `/config`. Hermes-management expose configuration at `/console`, so we can unify this.
=> Fix: serve hermes-console by NodeJS

hermes-console/bower.json, hermes-console/static/index.html, hermes-console/static/js/console/filters/FiltersRepository.js
This PR fixes https://github.com/allegro/hermes/issues/1303. Filter debug does not support unicode strings. When you use unicode strings in filter debug no result is returned and an error is displayed in a console. 
Example content
```json
{"a": "★"}
```
causes
```
Error: String contains an invalid character
verify@http://localhost:8090/ui/js/console/filters/FiltersRepository.js:8:103
```
The error is thrown from
https://github.com/allegro/hermes/blob/fa416ab9f0c6711a1f443e76e23d38fd225cd696/hermes-console/static/js/console/filters/FiltersRepository.js#L8
`btoa` does not support unicode (try to run `btoa("★")` in JS console). 
Possible solutions:
- use base64 encoder which handles unicode (suggested in https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem)
- encode …
=> fixes #1303 | hermes-console: support unicode in filter debug

hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/UiResource.java
This PR fixes regression introduced in https://github.com/allegro/hermes/pull/1381. Currently HTML content is returned with content type \*/\*.
Before https://github.com/allegro/hermes/pull/1381:
```sh
$ curl http://localhost:8090/ui/index.html -I -s | grep -i content-type:
Content-Type: text/html
$ curl http://localhost:8090/ui/index.html\#/groups -I -s | grep -i content-type:
Content-Type: text/html
```
Current behaviour:
```sh
$ curl http://localhost:8090/ -I -s | grep -i content-type:
Content-Type: */*;charset=UTF-8
$ curl http://localhost:8090/\#/groups -I -s | grep -i content-type:
Content-Type: */*;charset=UTF-8
```
After fix:
```sh
$ curl http://localhost:8090/ -I -s | grep -i content-type:
Content-Type: text/html;charset=UTF-8
$ curl http://localhost:8090/\#/groups -I -s | grep …
```
=> [hermes-management] restore text/html content-type for web pages

.github/workflows/release.yml, hermes-benchmark/src/jmh/java/pl/allegro/tech/hermes/benchmark/MessageRepositoryBenchmark.java, hermes-frontend/build.gradle, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/chronicle/ChronicleMapClosedException.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/buffer/chronicle/ChronicleMapMessageRepository.java
Added additional logging as we would like to know if there are any messages in the backup storage while stopping hermes-frontend instances. 
Benchmarks show that the lock added in `ChronicleMapMessageRepository` has no significant performance impact:
```
./gradlew jmh -Pjmh.timeOnIteration=10s -Pjmh.timeOnWarmupIteration=10s -Pjmh.threads=200
...
Benchmark                                  Mode  Cnt           Score            Error  Units
MessageRepositoryBenchmark.baselineSave    avgt    4  2491959675.090 ± 6214378958.477  ns/op
MessageRepositoryBenchmark.hermesImplSave  avgt    4  2526235175.176 ± 3376593190.719  ns/op
```
=> Log backup storage size on shutdown

build.gradle, hermes-api/src/main/java/pl/allegro/tech/hermes/api/OfflineRetransmissionRequest.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/OffsetRetransmissionDate.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/jackson/OffsetDateTimeSerializer.java, hermes-management/build.gradle, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/BlacklistEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/ConsoleEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/GroupsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/MigrationsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/ModeEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/OAuthProvidersEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/OfflineRetransmissionEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/OwnersEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/RolesEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SchemaEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/WorkloadConstraintsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/mappers/ConstraintViolationMapper.java, hermes-test-helper/build.gradle, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/client/Hermes.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java
`KafkaRetransmissionServiceTest` was unstable due to stochastic way of serialising `OffsetDateTime` to JSON format. Sometimes Jersey client in integration tests was serialising `OffsetDateTime` with _ObjectMapper_ having _JavaTimeModule_ registered, sometimes _ObjectMapper_ had no module registered at all. 
When tests were failing, `BeanSerializerFactory` instance was exactly the same one as the one created by `ConfluentSchemaRegistryStarter ` during environment preparation. 
When tests were passing, `BeanSerializerFactory` instance differed from the one created during environment preparation.
=> Fixed unstable KafkaRetransmissionServiceTest and updated dependencies

hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/endpoint/RemoteServiceEndpoint.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java, integration/src/test/resources/logback-test.xml
Fixed unstable:
- `JettyMessageSenderTest.shouldNotRedirectMessage`,
- `PublishingTest.shouldPublishWithDelayAndConsumeMessage`
Also, set `warn` logging level for `org.apache.kafka` loggers.
=> Fix flaky tests

build.gradle, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/mappers/ConstraintViolationMapper.java
Recently upgraded jersey (from `2.26` to `2.35`) brings jackson `2.12.2` as a transitive dependency, which is not compatible with the version defined explicitly in the project: `2.11.4`. It causes a few issues when hermes itself is pulled in as an external dependency. For now I decided to downgrade jersey. In the next step we can upgrade both dependencies - jersey and jackson.
=> fix: use jackson 2.11.4 in the whole project

hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockExpect.java, hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockAvroTest.groovy, hermes-mock/src/test/groovy/pl/allegro/tech/hermes/mock/HermesMockJsonTest.groovy
__hermes-mock__ was not waiting for messages to be send to WireMock. It was causing _HermesMockException_, for example:
```
Caused by: pl.allegro.tech.hermes.mock.HermesMockException: Hermes mock did not receive 1 messages, got 0
at pl.allegro.tech.hermes.mock.HermesMockExpect.expectSpecificMessages(HermesMockExpect.java:70)
at pl.allegro.tech.hermes.mock.HermesMockExpect.assertMessages(HermesMockExpect.java:57)
at pl.allegro.tech.hermes.mock.HermesMockExpect.avroMessagesOnTopic(HermesMockExpect.java:49)
at pl.allegro.tech.hermes.mock.HermesMockExpect.singleAvroMessageOnTopic(HermesMockExpect.java:33)
```
Affected by this bug public hermes-mock methods were:
- singleJsonMessageOnTopicAs
- jsonMessagesOnTopicAs
- singleAvroMessageOnTopic
- avroMessagesOnTopic
=> Fixed bug in hermes-mock causing HermesMockException

.github/workflows/ci.yml, hermes-console/static/partials/modal/messagePreview.html
Previously, Message preview modal was rendering data in incorrect way.
For `/topics/{topic}/preview/cluster/{cluster}/partition/x/offset/y` server response JSON:
```json
{
"id": 123457,
"__metadata": {
"x-request-id": "685bce4e-1254-430e-8678-7caf905d2c2b",
"messageId": "a71c5e1f-4213-4c07-93a1-92cbcffef189",
"timestamp": "1642513311760"
}
}
```
messagePreview modal was trying to render response by accessing:
```
metadata.id
metadata.timestamp
message
```
which was invalid and was resulting in empty fields rendered for final user.
=> Fixed Message preview modal

hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/service/KafkaRawMessageReader.java
**Description of the problem:**
When fetching message preview from Kafka by using `@Path("/{topicName}/preview/cluster/{brokersClusterName}/partition/{partition}/offset/{offset}")` endpoint, result was *"sometimes"* 200, and *"sometimes"* 404 (for valid partition and offset params). After investigation I've found that way to reproduce this bug is:
1. Start hermes-management,
2. Call `/partition/{partition}/offset/{offset}` endpoint with valid params will result in 200 response,
3. Wait more than 60 seconds,
4. Call `/partition/{partition}/offset/{offset}` again, and it will response with 404,
5. Then, immediately after 404 perform another `/partition/{partition}/offset/{offset}` call - this time, it will result wit 200 response.
It occurred that waiting more than 60 seconds between calls …
=> Fixed issue with inconsistent KafkaRawMessageReader reads resulting in both 200s and 404s.

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Owner.java, hermes-console/static/js/console/owner/OwnerName.js, hermes-console/static/partials/ownerName.html
This PR adds possibility for `OwnerSource` to define url for each returned `Owner`. Owner's url is used in _hermes-console_ in _topic_ and _subscription_ views. 
**How it looks?**
When there is no url provided, then owner is not-clickable:
But if call to `/sources/{source}/{id}` will return Owner with url, then owner has a proper link:
=> Added possibility to define a clickable link to topic and subscription owner

.github/workflows/ci.yml, hermes-api/src/main/java/pl/allegro/tech/hermes/api/Owner.java, hermes-test-helper/build.gradle, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/retry/Retry.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/retry/RetryListener.java, hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/consumers/AbstractLogRepositoryTest.java, hermes-tracker/src/test/java/pl/allegro/tech/hermes/tracker/frontend/AbstractLogRepositoryTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/PublishingTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/auth/FrontendAuthenticationConfigurationTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/HermesIntegrationEnvironment.java
In this PR I'm trying to resolve issues with failing CI.
1. Fixed issue with failing CrowdOwnerSourceIntegrationTest.shouldCrowdServiceBeCalledOnce and CrowdOwnerSourceIntegrationTest.shouldReturnTwoResultsFromCrowd tests
2. [Turned off fast-failing CI](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast)
3. Fixed possible issue in `PublishingTest.shouldNotConsumeMessagesWhenSubscriptionIsSuspended` test which looked this way:
```
2022-01-31T15:57:14.6136865Z Gradle suite > Gradle test > pl.allegro.tech.hermes.integration.PublishingTest.shouldNotConsumeMessagesWhenSubscriptionIsSuspended SKIPPED
2022-01-31T15:57:17.5130401Z 
2022-01-31T15:57:17.5131668Z Gradle suite > Gradle test > …
```
=> Fix some CI failures

hermes-common/src/main/java/pl/allegro/tech/hermes/common/exception/RepositoryNotAvailableException.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java, hermes-console/static/js/console/Visibility.js, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/BlacklistEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/GroupsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/OAuthProvidersEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SchemaEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/SubscriptionsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/TopicsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/WorkloadConstraintsEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/storage/StorageConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/auth/RequestUser.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/blacklist/TopicBlacklistService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/dc/MultiDatacenterRepositoryCommandExecutor.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/group/GroupService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/oauth/OAuthProviderService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicContentTypeMigrationService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/workload/constraints/WorkloadConstraintsService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/kafka/MultiDCAwareService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/migration/owner/SupportTeamToOwnerMigrator.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/dc/MultiDatacenterRepositoryCommandExecutorTest.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/group/GroupServiceSpec.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorTest.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorWithRealApiPreconditionsTest.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/workload/constraints/WorkloadConstraintsServiceTest.groovy
Until now when _hermes-management_ was in `readOnly || readOnlyAdmin` mode, no one could edit topics, subscriptions or groups from _hermes-console_. Change introduced in this PR allows admin to perform __write__ operations using _hermes-console_ UI on topics, subscriptions and groups, even when _hermes-management_ is in read only mode.
=> During read-only mode admin can perform changes is hermes-console

integration/src/integration/java/pl/allegro/tech/hermes/integration/IntegrationTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/AuditEventMockStarter.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/EnvironmentAware.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/HermesIntegrationEnvironment.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/env/SharedServices.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/helper/AuditEventEndpoint.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/GroupManagementTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/TopicManagementTest.java, integration/src/test/resources/application.yaml
__Before:__
During integration tests `/audit-events` endpoint was created only when we wanted to verify audit events. It was created with usage of _RemoteServiceEndpoint_. Only then, when proper stubbing was defined, WireMock used in _RemoteServiceEndpoint_ handled requests properly. Unfortunately, in every other test (where `new RemoteServiceEndpoint(SharedServices.services().serviceMock(), "/audit-events");` was not used) requests send to `/audit-events` endpoint were not handled properly, resulting ___very long___ in error message:
```
2022-02-03T12:45:03.7035227Z     2022-02-03 12:45:03.604 ERROR WireMock - Request was not matched as there were no stubs registered:
2022-02-03T12:45:03.7038417Z     {
2022-02-03T12:45:03.7039072Z       "url" : "/audit-events", …
```
=> Test living audit events endpoint

hermes-console/static/partials/ownerSelector.html
**Until now:**
User could either choose owner from dropdown, or type it manually. Typed in owners did not contained all required data.
**Solution:**
When owner source has _autocompletion_, hermes-console user has to choose one of proposed owners from dropdown list. User can type in owner manually, but without accepting concrete owner from dropdown, form will remain invalid.
=> Choosing owner from autocomplete source prevents manual entries

CHANGELOG.md, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/DirectBufferPool.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/DirectBufferUtils.java
By default native memory used by a given instance of `DirectByteBuffer` is released when the object is garbage collected. We don't want to wait for the GC and release the memory as soon as possible. Although the implementation may seem hacky, it seems to be the only possible way for now ([other projects approach this issue in a similar way](https://github.com/akka/akka/blob/331db9b8f8b02edb9370628d62ca53a55ed037e7/akka-actor/src/main/scala/akka/io/DirectByteBufferPool.scala#L80-L107)).
=> Explicitly releasing direct buffers in hermes-consumers

hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/GroupsEndpoint.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/GroupManagementTest.java
**Until now:**
Only admins were able to remove empty groups.
**After this PR:**
Any logged-in user is able to remove empty groups.
=> Any logged-in user can remove group

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java
This PR is a bug fix. Regarding to the documentation `close()` method can also throw `InterruptException` and `KafkaException`. Prior to this fix, throwing these exceptions could interfere with code execution and for example shutdown of the ConsumerSupervisor
=> Fixed exceptions catching while closing consumer

.github/workflows/release.yml
**Problem:**
Running `release.yml` GitHub Action resulted with error `"message": "Bad credentials"` when calling `POST https://api.github.com/repos/allegro/hermes/releases`.
I've added required permissions for GITHUB_TOKEN to create new release, as described in:
- [contents permission documentation](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-contents),
-  [example call GitHub REST API with permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api)
=> Fix release notes generation

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/KafkaHeaderNameProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/TopicLoadingProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaHeaderFactory.java
* restored the default value of `frontend.startup.topic.loading.metadataRefreshJob.enabled`
* fixed the name of the parameter `consumer.kafka.header.name`
* fixed setting the value of the header containing `schemaId`
=> hermes-frontend configuration fixes

hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/workload/weighted/ScoringTargetWeightCalculatorTest.groovy
This PR makes [ScoringTargetWeightCalculatorTest](https://github.com/allegro/hermes/pull/1575/commits/534a5b789a1227f85b965c384a23fb883fe5acfc) robust to float comparison (test currently fails on M1 mac)
=> Fix fragile float based ScoringTargetWeightCalculatorTest

build.gradle, docs/docs/quickstart.md, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ConfluentSchemaRegistryContainer.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ImageTags.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/KafkaContainerCluster.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ZookeeperContainer.java, integration/build.gradle
This PR enables developers to run integration tests on M1 macs, specifically:
- `testcontainers` and `toxiproxy` image were updated to allow running `toxiproxy` native arm64 image
- ability to specify confluent image tag via gradle task property was added, so developers can run tests with arm images:
```bash
./gradlew clean integrationTest -PconfluentImagesTag=7.2.2.arm64
```
=> add ability to run integration tests on m1 mac

integration/src/integration/java/pl/allegro/tech/hermes/integration/management/OfflineRetransmissionManagementTest.java
This PR restores proper assertions for all fields. Seem that check for `startTimestamp` was removed in
https://github.com/allegro/hermes/commit/0fb614ac3d57ba0d2ebe151dba2866256832792b#diff-02c5d8eba09311acf3c237b806eb0aea7036af9452da83afbba951bbf8283847
=> Restore assertion in OfflineRetransmissionManagementTest

docs/docs/configuration/rate-limiting.md
Addresses #1436
There is no more option to set `consumer.maxrate.strategy` so this docs is not needed any more. Other docs regarding rate-limiting seems up to date to my knowlage
=> Remove deprecated max rate negotiation docs

.gitignore, integration/README.md, integration/build.gradle, integration/src/integration/e2e/cypress.config.js, integration/src/integration/e2e/cypress/e2e/groups.cy.js, integration/src/integration/e2e/cypress/support/generators.js, integration/src/integration/e2e/package-lock.json, integration/src/integration/e2e/package.json, integration/src/integration/e2e/reporter-config.json, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/CypressTest.java
This PR adds infrastructure for end-to-end frontend tests. Tests are based on [Cypress framework](http://cypress.io) and [testcontainers module for running Cypress tests](https://github.com/wimdeblauwe/testcontainers-cypress). 
PR contains a single test which verifies adding new new group. More tests can be easily added in the future (maybe by other Hacktoberfest participants). 
`CypressTest` run tests using testcontainers. You can also run tests in Cypress app:
Cypress allows to create tests independent from the frontend framework (apart from CSS selectors). Such tests can be useful in case of https://github.com/allegro/hermes/issues/1142.
=> End-to-end frontend tests

.github/workflows/checkstyle.yml, build.gradle
Prior to this change, the check responsible for performing static code analysis would not fail if any violations were reported. Additionally, only `reviewdog` comments regarding the gradle module that happened to be the last on the list built in the step `Run reviewdog` were posted (due to a name collision - see the `-name` parameter of the `reviewdog` GH action).
=> Fix checkstyle action

build.gradle, integration/build.gradle
[JCenter has been deprecated](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) for some time and [seems to be completely down today](https://stackoverflow.com/questions/74258160/is-jcenter-down-permanently-31-oct).
=> Moved away from jcenter

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/KafkaConsumerProperties.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaConsumerParameters.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaMessageReceiverFactory.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/PartitionAssignmentStrategy.java
The main advantage of the newer (sticky, cooperative) partition assignment strategies is the shorter time needed to perform rebalances. We would like to try them out and test how they will work in our environment.
=> Added possibility to configure partition assignment strategy

integration/build.gradle
Setting preserve order to true might be beneficial for e2e test stability https://docs.gradle.org/current/userguide/java_testing.html#test_execution_order
=> preserve testng test order

build.gradle, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/workload/constraints/WorkloadConstraintsServiceTest.groovy, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/KafkaContainerCluster.java
This revolves the problem introduced in: https://github.com/allegro/hermes/commit/1f990bc94282a9b6990940a85217f17d86c5dbe2, which caused groovy tests to not run in `hermes-frontend` and `hermes-management`. 
The problem was that testcontainers above version `1.15.3` depend on `spock>=2 groovy>=3`(https://github.com/testcontainers/testcontainers-java/blob/main/modules/spock/build.gradle#L9), and we are using spock version: `1.3-groovy-2.5`. One solution would be to bump spock but version 2 changed the test execution engine which breaks tests using wiremock with `ClassRule`. I have created separate issue for this: https://github.com/allegro/hermes/issues/1647
=> fix groovy version collision

hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/auth/TestRequestUser.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/subscription/validator/InflightSizeValidatorTest.groovy, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/SubscriptionBuilder.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/FilteringJsonTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/SubscriptionManagementTest.java
This PR changes the way in which inflight queue size for consumers is calculated. 
Prior to this change inflight queue size was calculated based on 2 values:
- subscriptionInflightSize - set per subscription, default value: 100
- globalInflightSize - global property configured by   `consumer.serialConsumer.inflightSize`, default value: 100
Final queue inflight size was calculated as `min(subscriptionInflightSize, globalInflightSize)`.
After this PR default `subscriptionInflightSize` will be set to `null`, and final size will be calculated as:  
```java
subscriptionInflightSize != null ? subscriptionInflightSize : globalInflightSize
```
subscriptionInflightSize will be configurable only by admin users from now on.
Deploying this version without any migration would cause inflight queue of …
=> Configurable consumer inflight queue size

.github/workflows/release.yml, docs/docs/user/java-client.md
"[Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#:~:text=Starting%201st%20June%202023%20workflows%20using%20save%2Dstate%20or%20set%2Doutput%20commands%20via%20stdout%20will%20fail%20with%20an%20error.)"
=> Update deprecated set-output and link

.github/workflows/ci.yml
> Remove Java version from job name so that required PR checks are independent of java version. E.g. Required check will be renamed from `Java 11 check` to `unitTests`. This will enable build which use different java version (e.g. Java 17/21) to pass all checks. We don't plan to support multiple Java version in the foreseeable future.
=> CI jobs name independent of Java version

build.gradle, docker/latest/consumers/Dockerfile, docker/latest/frontend/Dockerfile, docker/latest/management/Dockerfile, hermes-client/build.gradle, hermes-common/src/test/groovy/pl/allegro/tech/hermes/test/IntegrationTest.groovy, hermes-mock/build.gradle
This PR
- fixes: https://github.com/allegro/hermes/issues/1683, by including missing transitive dependencies for hermes-mock
- fixes https://github.com/allegro/hermes/issues/1684 and https://github.com/allegro/hermes/pull/1673#issuecomment-1606271069 by fixing jackson version clash and providing hermes java 17 docker images
=> Fix java 17 and spring-boot 2.7.7 migration bugs

docs/docs/user/hermes-mock.md
This PR adds missing documentation for https://github.com/allegro/hermes/blob/c817e3263ea514e1e4022e90479030a84673d19f/hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockExpect.java#L45 and for https://github.com/allegro/hermes/blob/c817e3263ea514e1e4022e90479030a84673d19f/hermes-mock/src/main/java/pl/allegro/tech/hermes/mock/HermesMockExpect.java#L53
=> Add missing HermesMockExpect documentation

.github/workflows/release.yml
In this PR I've simplified and fixed process of generation GitHub Release page.
Until now, this part of `release` action didn't work due to issue with JSON serialisation. I've decided to simplify code generating Github Release page by using [`gh release create`](https://cli.github.com/manual/gh_release_create) CLI command instead of calling API manually.
=> Simplify and fix generation of GitHub Release page

.github/workflows/checkstyle.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/gradle-wrapper-validation.yml, .github/workflows/markdown-links-check.yml, .github/workflows/release.yml
Avoid using versions that using Node 12 environment that generate warnings in workflow runs. Use new versions instead that depend on Node 16.
Also remove unnecessary chmod on gradlew in workflows
=> Bump GitHub actions

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Consumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyMessageBatchSender.java
When consumer process is deemed unhealthy it is interrupted. There were places in code when `InterruptedException` was catched but interrupted status was not restored. Because of that `ConsumerProcess#run` was unable to detect that the thread was interrupted:
```java
while (running && !Thread.currentThread().isInterrupted()) {
```
consumer process was still sending messages to subscribers but was marked as unhealthy and its messages were not commited. This situation would last until consumer was restarted. 
In this PR `interrupted` statuses are restored, enabling unhealthy consumer process to exit.
=> Fix handling of interrupts

build.gradle, hermes-client/build.gradle, hermes-frontend/build.gradle, integration/build.gradle
Make dependencies back optional. They were made required when Spring Boot 2.7 support was added. Most of those dependencies are related to specific sender implementation and the user is supposed to choose one and provide the needed client library.
=> Bring back optional dependencies

hermes-console-vue/json-server/db.json, hermes-console-vue/json-server/subscriptions.json, hermes-console-vue/src/composables/subscription/use-create-subscription/useCreateSubscription.ts, hermes-console-vue/src/composables/subscription/use-form-subscription/form-mapper.ts, hermes-console-vue/src/composables/subscription/use-form-subscription/types.ts, hermes-console-vue/src/composables/subscription/use-form-subscription/useFormSubscription.ts, hermes-console-vue/src/dummy/subscription-form.ts, hermes-console-vue/src/dummy/subscription.ts, hermes-console-vue/src/views/subscription/properties-card/PropertiesCard.spec.ts, hermes-console-vue/src/views/subscription/properties-card/PropertiesCard.vue, hermes-console-vue/src/views/subscription/subscription-form/SubscriptionForm.vue
This PR re-introduces editing `endpointAddressResolverMetadata`. In old hermes-console there was support for `boolean`, `text`, `number` and `select` properties. For now only `boolean` support is re-introduced. Please submit issues if you need support for other property types.
In old hermes console `boolean` values had 3 possible values: `null`, `true`, `false`. When editing subscription for the first time after introducing new property it would appear on form but it would remain `null` until its value was explicitly changed. In this PR default value of `false` is introduced for `boolean` properties meaning that a first update to subscription after creating a new metadata property in config will result in implicitly setting this value to `false`.
=> support for editing boolean endpoint address resolver metadata properties

integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/client/HermesTestClient.java, integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/client/ManagementTestClient.java, integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/HermesExtension.java, integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/HermesInitHelper.java, integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/HermesManagementTestApp.java, integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/setup/TestUser.java, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/QueryEndpointTest.java, integration/src/integration/java/pl/allegro/tech/hermes/integration/management/QueryEndpointTest.java
All QueryEndpointTests except ones relying on prometheus stub rewritten
=> rewrite query endpoint test

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicWithSchema.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/builder/TopicBuilder.java, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java
This is a preliminary step to introduce fallback to a remote datacenter in case of any failures with the local Kafka cluster while publishing. The flag introduced here, when set to true, will enable the fallback for a given topic and disable persistent buffers for it. The mechanism respecting this flag will be added as a follow-up.
=> Add flag 'fallback to remote datacenter'

build.gradle
The main reason why we need this update is the bug reported here: https://github.com/jetty/jetty.project/issues/11372. Version 12.0.7 includes a fix for this bug.
=> Update jetty to 12.0.7

hermes-common/src/main/java/pl/allegro/tech/hermes/common/metric/ProducerMetrics.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FailFastKafkaProducerProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FailFastLocalKafkaProducerProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FailFastRemoteKafkaProducerProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FrontendProducerConfiguration.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSender.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSendersFactory.java, integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/assertions/PrometheusMetricsAssertion.java, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/KafkaProducerMetricsTest.java
1. Split fail fast producer config to local / remote
2. Expose kafka send_total metric which can be used to calculate true record send  rate (with retries)
=> Multi datacenter senders improvements

build.gradle, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FailFastLocalKafkaProducerProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FailFastRemoteKafkaProducerProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/KafkaProducerProperties.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSender.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSendersFactory.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaProducerParameters.java, hermes-frontend/src/test/groovy/pl/allegro/tech/hermes/frontend/producer/kafka/LocalDatacenterMessageProducerIntegrationTest.groovy, hermes-test-helper/src/main/java/pl/allegro/tech/hermes/test/helper/containers/ImageTags.java, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/KafkaRetransmissionServiceTest.java
Bump kafka clients in order to make use of [Strictly Uniform Sticky Partitioner](https://cwiki.apache.org/confluence/display/KAFKA/KIP-794%3A+Strictly+Uniform+Sticky+Partitioner). Rewrite / remove tests which depend on previous partitioner behaviour i.e. round robin.
=> bump kafka clients to version 3.6.2

hermes-console/src/composables/subscription/use-subscription-filters-debug/useSubscriptionFiltersDebug.ts
This resolves: https://github.com/allegro/hermes/issues/1838
Filter debug endpoint expects message to be base64 encoded byte array. Previous solution using `btoa` was not working with all unicode characters.
=> add support for all unicode characters in message filters debug

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/publishing/handlers/PublishingHandler.java
Transition to failed state when publishing handler throws exception. Without it a timeout handler would run after a response was already sent. This would in turn always log 
```
Not sending error message to a client as response has already been started.
```
=> transition to error state upon failing publishing handler

build.gradle, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaMessageSender.java
Downgrade Kafka clients to version prior to https://github.com/allegro/hermes/commit/0a6cfd7a39ba7a5be9063f53fdf02daf8b149824. With Kafka client 3.6.2 Hermes-frontend latency is greatly increased across all percentiles. We suspect that this may be because of internal producer changes or misconfiguration with new version.
=> Downgrade kafka clients

hermes-api/src/main/java/pl/allegro/tech/hermes/api/RetentionTime.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/SubscriptionPolicy.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/validator/SubscriptionValidator.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/subscription/validator/InflightSizeValidatorTest.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorWithRealApiPreconditionsTest.groovy, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/SubscriptionManagementTest.java
Allow topics with `retentionTime` exceeding maximum and subscriptions with not null `inflightSize` to be modifiable by regular users. Previously if admin set a value of one of those fields to admin-only value it made the topic / subscription uneditable by regular users.
=> InflightSize and retentionTime validation improvements

hermes-console/src/views/search/topic-search-results/TopicSearchResults.vue
Fixed redirect link for blank click on search topic.
Previously links contained double slash.
=> Fix topic search redirect link

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Message.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSender.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/consumer/sender/http/JettyBroadCastMessageSenderTest.groovy
This PR implements a fix for a bug that would cause a broadcast message to be undeliverable. Consider a following scenario:
1. Message is being sent to service `A` with instances `A1`, `A2` and `A3`
2. Message is sent successfully to instances `A1` and `A2` but fails to be delivered to `A3`
3. Sent is being retried
4. The set of instances changes to just `A1` and `A2` (perhaps there was ongoing rolling upgrade and `A3` was terminated)
Previously, when that situation occurred the message would be retried until its TTL expired - `A1` and `A2` were already marked as succeeded and so they were not added to `children` of `MultiMessageSendingResult`. `children` was an empty list which was considered a failure so the message was retried. This would go on as long as the set of uris returned from …
=> Allow for 'empty' broadcast send attempt

hermes-api/src/main/java/pl/allegro/tech/hermes/api/Topic.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/TopicWithSchema.java, hermes-api/src/test/java/pl/allegro/tech/hermes/api/TopicTest.java, hermes-common/src/main/java/pl/allegro/tech/hermes/common/di/factories/ObjectMapperFactory.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/test/IntegrationTest.groovy, hermes-common/src/test/java/pl/allegro/tech/hermes/common/di/ObjectMapperFactoryTest.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/CommonConfiguration.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/CommonConfiguration.java, hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/TopicDefaultsProperties.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/ManagementConfiguration.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/config/TopicProperties.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/TopicService.java, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java
Make a default value for topic property `fallbackToRemoteDatacenterEnabled` configurable via:
- `topic.defaultFallbackToRemoteDatacenterEnabled` for management
-  `frontend.topic.defaults.fallbackToRemoteDatacenterEnabled` for frontend 
This will enable configuring whether newly created topics and topics with missing property should have fallback turned on by default or not.
=> allow configuration of default value for remoteDatacenterFallbackEnabled

hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidator.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorTest.groovy, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/topic/validator/TopicValidatorWithRealApiPreconditionsTest.groovy, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/TopicManagementTest.java
- Allow regular users to only use default value of fallbackToRemoteDatacenterEnabled when creating topic
- Do not allow users to modify fallbackToRemoteDatacenterEnabled on existing topic
=> Improved topic validation

hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java
Batch subscription currently do not support hot reload of filters, probably someone forgot to call:
`receiver.updateSubscription(subscription)`
=> update batch receiver on subscription update

hermes-console/json-server/db.json, hermes-console/json-server/routes.json, hermes-console/json-server/server.ts, hermes-console/src/api/hermes-client/index.ts, hermes-console/src/composables/sync/use-sync/useSync.spec.ts, hermes-console/src/composables/sync/use-sync/useSync.ts, hermes-console/src/dummy/groupInconsistency.ts, hermes-console/src/i18n/en-US/index.ts, hermes-console/src/mocks/handlers.ts, hermes-console/src/store/consistency/useConsistencyStore.spec.ts, hermes-console/src/store/consistency/useConsistencyStore.ts, hermes-console/src/views/admin/consistency/inconsistent-group/InconsistentGroup.vue, hermes-console/src/views/admin/consistency/inconsistent-metadata/InconsistentMetadata.spec.ts, hermes-console/src/views/admin/consistency/inconsistent-metadata/InconsistentMetadata.vue, hermes-console/src/views/admin/consistency/inconsistent-topic/InconsistentTopic.vue, hermes-management/src/main/java/pl/allegro/tech/hermes/management/api/ConsistencyEndpoint.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/consistency/DcConsistencyService.java, hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/consistency/SynchronizationException.java, hermes-management/src/test/groovy/pl/allegro/tech/hermes/management/domain/consistency/StorageSyncSpec.groovy
Allow admins to perform storage synchronization using UI. Admin selects "primary" DC for group/topic/subscription and its content is propagated to nodes in other DCs.
After synchronization only the group that was synchronized is refreshed so consistency view shows up to date information without making an expensive check for all groups
=> Synchronize zookeeper clusters with UI

hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperBasedRepository.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/cache/HierarchicalCacheTest.groovy
Rewrite deprecated curator API related to transactions
resolve #1886
=> Rewrite deprecated curator API - transactions

hermes-console/json-server/db.json, hermes-console/json-server/routes.json, hermes-console/src/api/hermes-client/index.ts, hermes-console/src/composables/topic/use-topic/useTopic.spec.ts, hermes-console/src/composables/topic/use-topic/useTopic.ts, hermes-console/src/i18n/en-US/index.ts, hermes-console/src/mocks/handlers.ts, hermes-console/src/views/topic/TopicView.vue, hermes-console/src/views/topic/subscriptions-list/SubscriptionsList.spec.ts, hermes-console/src/views/topic/subscriptions-list/SubscriptionsList.vue
This PR adds a convenient feature that allows users to copy all client emails for a given topic to the clipboard with a single click. The functionality is accessible via a button added to the `Subscriptions` list.
After the emails are successfully copied, a confirmation notification is displayed to the user (and its clipboard content becomes `client1@allegro.com,client2@allegro.com,client3@allegro.com`):
If an error occurs during the operation, an error notification informs the user of the issue:
=> Add a button to copy topic clients to clipboard (#1923)

integration-tests/src/common/java/pl/allegro/tech/hermes/integrationtests/assertions/PrometheusMetricsAssertion.java
Most probably after update of prometheus dependencies, test `BrokerLatencyReportingTest > shouldReportBrokerLatencyMetrics()` stopped working because `PrometheusMetricsAssertion` always requires the metric value to be in floating point format, which is not the case anymore, the above mentioned test fails with `java.lang.IllegalStateException: Unexpected line: hermes_frontend_broker_latency_seconds_count{ack="LEADER",broker="localhost"} 1` but it should succeed.
I changed the `PrometheusMetricsAssertion` to allow both floating point and decimal numbers in assertions.
=> Allow both decimal and floating point numbers in metrics assertion pattern

hermes-common/src/main/java/pl/allegro/tech/hermes/common/kafka/offset/SubscriptionOffsetChangeIndicator.java, hermes-common/src/main/java/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionOffsetChangeIndicator.java, hermes-common/src/test/groovy/pl/allegro/tech/hermes/infrastructure/zookeeper/ZookeeperSubscriptionOffsetChangeIndicatorTest.groovy, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/BatchConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/Consumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/SerialConsumer.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/batch/MessageBatchReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/offset/ConsumerPartitionAssignmentState.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/MessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/ThrottlingMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/UninitializedMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/FilteringMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/receiver/kafka/KafkaSingleThreadedMessageReceiver.java, hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/supervisor/process/Retransmitter.java, hermes-consumers/src/test/groovy/pl/allegro/tech/hermes/consumers/supervisor/process/ConsumerStub.groovy
**Why:**
The current implementation of the Retransmitter::reloadOffsets method contains a race condition. Multiple consumer instances can execute this code simultaneously, which may lead to unpredictable behavior.
Offsets are stored in ZooKeeper per partition, for example: `[1:{123}, 2:{345}, 3:{567}, 4:{678}]`.
The method first fetches the entire list of available partitions from ZooKeeper (`[1,2,3,4]`), then retrieves the specific offsets for each partition. The fetched offsets are processed for partitions assigned to the consumer and subsequently deleted from ZooKeeper. For instance, if consumer1 is assigned partitions `[1,2]`, it will process these offsets and delete them, leaving only partitions `[3,4]` in ZooKeeper.
The issue arises when multiple consumers execute this process …
=> SKYEDEN-3020 | Handle retransmission zookeeper race condition

docker/latest/consumers/Dockerfile, docker/latest/frontend/Dockerfile, docker/latest/management/Dockerfile
Currently `docker-compose up` fails (`podman compose up` in my case):
```
>>>> Executing external compose provider "/Users/x/.docker/cli-plugins/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<
WARN[0000] /Users/x/workspaces/github/hermes/docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 0/3
diff --git a/docker/.env b/docker/.env
index bb66fb7f4..e3a99bcdb 100644
--- a/docker/.env
+++ b/docker/.env
⠦ Service frontend    Building                                                                                                                                                                                                       31.7s
⠦ Service management  Building …
```
=> Fix docker - use existing JDK image

hermes-api/src/main/java/pl/allegro/tech/hermes/api/subscription/metrics/MessageProcessingDurationMetricOptions.java, hermes-api/src/main/java/pl/allegro/tech/hermes/api/subscription/metrics/SubscriptionMetricsConfig.java, integration-tests/src/integrationTest/java/pl/allegro/tech/hermes/integrationtests/management/SubscriptionManagementTest.java
Message processing time metric was introduced in https://github.com/allegro/hermes/pull/1958. 
When `thresholdsMilliseconds` contains invalid, negative value (e.g. `-100`) then:
- `Failed to process signal Signal(2480, UPDATE_SUBSCRIPTION...` is logged. 
- `hermes_consumers_subscription_message_processing_time metric` is not gathered, because old micrometer meter is removed and new cannot be created
- Invalid value is stored and returned by rest API
After setting valid value of `thresholdsMilliseconds`  everything works properly.
This PR fixes the bug and require positive values of `thresholdsMilliseconds`. 
Now negative vales are not accepted and Bad Request is returned:
```http
PUT http://localhost:8090/topics/g23.t1/subscriptions/s1
Content-Type: application/json
{
"metricsConfig": { …
```
=> Require positive values of thresholdsMilliseconds

hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/config/FrontendConfiguration.java, integration-tests/src/slowIntegrationTest/java/pl/allegro/tech/hermes/integrationtests/MessageBufferLoadingTest.java
Otherwise, when starting hermes-frontend without a disk attached we are getting an error.
=> Omit creating backup storage beans when it is disabled
